<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Canton;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Canton::create(['name'=>'San Lorenzo', 'id_province'=>'8']);
        Canton::create(['name'=>'Eloy Alfaro', 'id_province'=>'8']);
        Canton::create(['name'=>'Rioverde', 'id_province'=>'8']);
        Canton::create(['name'=>'Esmeraldas', 'id_province'=>'8']);
        Canton::create(['name'=>'Muisne', 'id_province'=>'8']);
        Canton::create(['name'=>'Atacames', 'id_province'=>'8']);
        Canton::create(['name'=>'Quininde', 'id_province'=>'8']);
        Canton::create(['name'=>'Tulcan', 'id_province'=>'4']);
        Canton::create(['name'=>'Mira', 'id_province'=>'4']);
        Canton::create(['name'=>'Espejo', 'id_province'=>'4']);
        Canton::create(['name'=>'Montufar', 'id_province'=>'4']);
        Canton::create(['name'=>'San Pedro de Huaca', 'id_province'=>'4']);
        Canton::create(['name'=>'Bolivar (Carchi)', 'id_province'=>'4']);
        Canton::create(['name'=>'Montalvo', 'id_province'=>'6']);
        Canton::create(['name'=>'Sigchos', 'id_province'=>'6']);
        Canton::create(['name'=>'La Mana', 'id_province'=>'6']);
        Canton::create(['name'=>'Latacunga', 'id_province'=>'6']);
        Canton::create(['name'=>'Saquisili', 'id_province'=>'6']);
        Canton::create(['name'=>'Pujili', 'id_province'=>'6']);
        Canton::create(['name'=>'Pangua', 'id_province'=>'6']);
        Canton::create(['name'=>'Salcedo', 'id_province'=>'2']);
        Canton::create(['name'=>'Guaranda', 'id_province'=>'2']);
        Canton::create(['name'=>'Las Naves', 'id_province'=>'2']);
        Canton::create(['name'=>'Echeandia', 'id_province'=>'2']);
        Canton::create(['name'=>'Caluma', 'id_province'=>'2']);
        Canton::create(['name'=>'Chimbo', 'id_province'=>'2']);
        Canton::create(['name'=>'San Miguel', 'id_province'=>'2']);
        Canton::create(['name'=>'Quero', 'id_province'=>'5']);
        Canton::create(['name'=>'Guano', 'id_province'=>'5']);
        Canton::create(['name'=>'Penipe', 'id_province'=>'5']);
        Canton::create(['name'=>'Riobamba', 'id_province'=>'5']);
        Canton::create(['name'=>'Colta', 'id_province'=>'5']);
        Canton::create(['name'=>'Chambo', 'id_province'=>'5']);
        Canton::create(['name'=>'Pallatanga', 'id_province'=>'5']);
        Canton::create(['name'=>'Guamote', 'id_province'=>'5']);
        Canton::create(['name'=>'Alausi', 'id_province'=>'5']);
        Canton::create(['name'=>'Cumanda', 'id_province'=>'5']);
        Canton::create(['name'=>'Salinas', 'id_province'=>'3']);
        Canton::create(['name'=>'La Troncal', 'id_province'=>'3']);
        Canton::create(['name'=>'Cañar', 'id_province'=>'3']);
        Canton::create(['name'=>'Suscal', 'id_province'=>'3']);
        Canton::create(['name'=>'El Tambo', 'id_province'=>'3']);
        Canton::create(['name'=>'Azogues', 'id_province'=>'3']);
        Canton::create(['name'=>'Biblian', 'id_province'=>'3']);
        Canton::create(['name'=>'Deleg', 'id_province'=>'1']);
        Canton::create(['name'=>'Sevilla de Oro', 'id_province'=>'1']);
        Canton::create(['name'=>'Paute', 'id_province'=>'1']);
        Canton::create(['name'=>'Guachapala', 'id_province'=>'1']);
        Canton::create(['name'=>'El Pan', 'id_province'=>'1']);
        Canton::create(['name'=>'Gualaceo', 'id_province'=>'1']);
        Canton::create(['name'=>'Chordeleg', 'id_province'=>'1']);
        Canton::create(['name'=>'Sigsig', 'id_province'=>'1']);
        Canton::create(['name'=>'Cuenca', 'id_province'=>'1']);
        Canton::create(['name'=>'Santa Isabel', 'id_province'=>'1']);
        Canton::create(['name'=>'Pucara', 'id_province'=>'1']);
        Canton::create(['name'=>'Camilo Ponce Enriquez', 'id_province'=>'1']);
        Canton::create(['name'=>'San Fernando', 'id_province'=>'1']);
        Canton::create(['name'=>'Giron', 'id_province'=>'1']);
        Canton::create(['name'=>'Nabon', 'id_province'=>'1']);
        Canton::create(['name'=>'Oña', 'id_province'=>'7']);
        Canton::create(['name'=>'El Guabo', 'id_province'=>'7']);
        Canton::create(['name'=>'Machala', 'id_province'=>'7']);
        Canton::create(['name'=>'Pasaje', 'id_province'=>'7']);
        Canton::create(['name'=>'Chilla', 'id_province'=>'7']);
        Canton::create(['name'=>'Zaruma', 'id_province'=>'7']);
        Canton::create(['name'=>'Santa Rosa', 'id_province'=>'7']);
        Canton::create(['name'=>'Atahualpa', 'id_province'=>'7']);
        Canton::create(['name'=>'Arenillas', 'id_province'=>'7']);
        Canton::create(['name'=>'Huaquillas', 'id_province'=>'7']);
        Canton::create(['name'=>'Las Lajas', 'id_province'=>'7']);
        Canton::create(['name'=>'Marcabeli', 'id_province'=>'7']);
        Canton::create(['name'=>'Balsas', 'id_province'=>'7']);
        Canton::create(['name'=>'Piñas', 'id_province'=>'7']);
        Canton::create(['name'=>'Chinchipe', 'id_province'=>'9']);
        Canton::create(['name'=>'Isabela', 'id_province'=>'9']);
        Canton::create(['name'=>'San Cristobal', 'id_province'=>'9']);
        Canton::create(['name'=>'Gualaquiza', 'id_province'=>'10']);
        Canton::create(['name'=>'El Empalme', 'id_province'=>'10']);
        Canton::create(['name'=>'Balzar', 'id_province'=>'10']);
        Canton::create(['name'=>'Colimes', 'id_province'=>'10']);
        Canton::create(['name'=>'Palestina', 'id_province'=>'10']);
        Canton::create(['name'=>'Santa Lucia', 'id_province'=>'10']);
        Canton::create(['name'=>'Pedro Carbo', 'id_province'=>'10']);
        Canton::create(['name'=>'Isidro Ayora', 'id_province'=>'10']);
        Canton::create(['name'=>'Lomas de Sargentillo', 'id_province'=>'10']);
        Canton::create(['name'=>'Nobol', 'id_province'=>'10']);
        Canton::create(['name'=>'Daule', 'id_province'=>'10']);
        Canton::create(['name'=>'Salitre', 'id_province'=>'10']);
        Canton::create(['name'=>'Samborondon', 'id_province'=>'10']);
        Canton::create(['name'=>'Yaguachi', 'id_province'=>'10']);
        Canton::create(['name'=>'Alfredo Baquerizo Moreno', 'id_province'=>'10']);
        Canton::create(['name'=>'Milagro', 'id_province'=>'10']);
        Canton::create(['name'=>'Simon Bolivar', 'id_province'=>'10']);
        Canton::create(['name'=>'Naranjito', 'id_province'=>'10']);
        Canton::create(['name'=>'General Antonio Elizalde', 'id_province'=>'10']);
        Canton::create(['name'=>'Coronel Marcelino Maridueña', 'id_province'=>'10']);
        Canton::create(['name'=>'El Triunfo', 'id_province'=>'10']);
        Canton::create(['name'=>'Duran', 'id_province'=>'10']);
        Canton::create(['name'=>'Guayaquil', 'id_province'=>'10']);
        Canton::create(['name'=>'Playas', 'id_province'=>'10']);
        Canton::create(['name'=>'Naranjal', 'id_province'=>'10']);
        Canton::create(['name'=>'Ibarra', 'id_province'=>'11']);
        Canton::create(['name'=>'San Miguel de Urcuqui', 'id_province'=>'11']);
        Canton::create(['name'=>'Cotacachi', 'id_province'=>'11']);
        Canton::create(['name'=>'Antonio Ante', 'id_province'=>'11']);
        Canton::create(['name'=>'Otavalo', 'id_province'=>'11']);
        Canton::create(['name'=>'Pimampiro', 'id_province'=>'11']);
        Canton::create(['name'=>'Portovelo', 'id_province'=>'12']);
        Canton::create(['name'=>'Saraguro', 'id_province'=>'12']);
        Canton::create(['name'=>'Loja', 'id_province'=>'12']);
        Canton::create(['name'=>'Chaguarpamba', 'id_province'=>'12']);
        Canton::create(['name'=>'Olmedo (Loja)', 'id_province'=>'12']);
        Canton::create(['name'=>'Catamayo', 'id_province'=>'12']);
        Canton::create(['name'=>'Paltas', 'id_province'=>'12']);
        Canton::create(['name'=>'Puyango', 'id_province'=>'12']);
        Canton::create(['name'=>'Pindal', 'id_province'=>'12']);
        Canton::create(['name'=>'Celica', 'id_province'=>'12']);
        Canton::create(['name'=>'Zapotillo', 'id_province'=>'12']);
        Canton::create(['name'=>'Macara', 'id_province'=>'12']);
        Canton::create(['name'=>'Sozoranga', 'id_province'=>'12']);
        Canton::create(['name'=>'Calvas', 'id_province'=>'12']);
        Canton::create(['name'=>'Gonzanama', 'id_province'=>'12']);
        Canton::create(['name'=>'Quilanga', 'id_province'=>'12']);
        Canton::create(['name'=>'Buena Fe', 'id_province'=>'13']);
        Canton::create(['name'=>'Valencia', 'id_province'=>'13']);
        Canton::create(['name'=>'Quevedo', 'id_province'=>'13']);
        Canton::create(['name'=>'Quinsaloma', 'id_province'=>'13']);
        Canton::create(['name'=>'Palenque', 'id_province'=>'13']);
        Canton::create(['name'=>'Mocache', 'id_province'=>'13']);
        Canton::create(['name'=>'Ventanas', 'id_province'=>'13']);
        Canton::create(['name'=>'Vinces', 'id_province'=>'13']);
        Canton::create(['name'=>'Baba', 'id_province'=>'13']);
        Canton::create(['name'=>'Puebloviejo', 'id_province'=>'13']);
        Canton::create(['name'=>'Urdaneta', 'id_province'=>'13']);
        Canton::create(['name'=>'Babahoyo', 'id_province'=>'13']);
        Canton::create(['name'=>'Pedernales', 'id_province'=>'14']);
        Canton::create(['name'=>'Chone', 'id_province'=>'14']);
        Canton::create(['name'=>'Flavio Alfaro', 'id_province'=>'14']);
        Canton::create(['name'=>'El Carmen', 'id_province'=>'14']);
        Canton::create(['name'=>'Jama', 'id_province'=>'14']);
        Canton::create(['name'=>'San Vicente', 'id_province'=>'14']);
        Canton::create(['name'=>'Sucre', 'id_province'=>'14']);
        Canton::create(['name'=>'Tosagua', 'id_province'=>'14']);
        Canton::create(['name'=>'Rocafuerte', 'id_province'=>'14']);
        Canton::create(['name'=>'Junin', 'id_province'=>'14']);
        Canton::create(['name'=>'Bolivar (Manabi)', 'id_province'=>'14']);
        Canton::create(['name'=>'Pichincha', 'id_province'=>'14']);
        Canton::create(['name'=>'Portoviejo', 'id_province'=>'14']);
        Canton::create(['name'=>'Jaramijo', 'id_province'=>'14']);
        Canton::create(['name'=>'Manta', 'id_province'=>'14']);
        Canton::create(['name'=>'Montecristi', 'id_province'=>'14']);
        Canton::create(['name'=>'Santa Ana', 'id_province'=>'14']);
        Canton::create(['name'=>'Jipijapa', 'id_province'=>'14']);
        Canton::create(['name'=>'Veinticuatro de Mayo', 'id_province'=>'14']);
        Canton::create(['name'=>'Olmedo (Manabi)', 'id_province'=>'14']);
        Canton::create(['name'=>'Puerto Lopez', 'id_province'=>'14']);
        Canton::create(['name'=>'Pajan', 'id_province'=>'14']);
        Canton::create(['name'=>'Chunchi', 'id_province'=>'15']);
        Canton::create(['name'=>'Palora', 'id_province'=>'15']);
        Canton::create(['name'=>'Pablo Sexto', 'id_province'=>'15']);
        Canton::create(['name'=>'Huamboya', 'id_province'=>'15']);
        Canton::create(['name'=>'Morona', 'id_province'=>'15']);
        Canton::create(['name'=>'Taisha', 'id_province'=>'15']);
        Canton::create(['name'=>'Sucua', 'id_province'=>'15']);
        Canton::create(['name'=>'Santiago', 'id_province'=>'15']);
        Canton::create(['name'=>'Logroño', 'id_province'=>'15']);
        Canton::create(['name'=>'Tiwintza', 'id_province'=>'15']);
        Canton::create(['name'=>'Limon Indanza', 'id_province'=>'15']);
        Canton::create(['name'=>'San Juan Bosco', 'id_province'=>'15']);
        Canton::create(['name'=>'El Chaco', 'id_province'=>'16']);
        Canton::create(['name'=>'Quijos', 'id_province'=>'16']);
        Canton::create(['name'=>'Archidona', 'id_province'=>'16']);
        Canton::create(['name'=>'Tena', 'id_province'=>'16']);
        Canton::create(['name'=>'Carlos Julio Arosemena Tola', 'id_province'=>'16']);
        Canton::create(['name'=>'Loreto', 'id_province'=>'17']);
        Canton::create(['name'=>'Francisco de Orellana', 'id_province'=>'17']);
        Canton::create(['name'=>'La Joya de los Sachas', 'id_province'=>'17']);
        Canton::create(['name'=>'Aguarico', 'id_province'=>'17']);
        Canton::create(['name'=>'Mera', 'id_province'=>'18']);
        Canton::create(['name'=>'Santa Clara', 'id_province'=>'18']);
        Canton::create(['name'=>'Arajuno', 'id_province'=>'18']);
        Canton::create(['name'=>'Pastaza', 'id_province'=>'18']);
        Canton::create(['name'=>'Puerto Quito', 'id_province'=>'19']);
        Canton::create(['name'=>'Pedro Vicente Maldonado', 'id_province'=>'19']);
        Canton::create(['name'=>'San Miguel de Los Bancos', 'id_province'=>'19']);
        Canton::create(['name'=>'Distrito Metropolitano de Quito', 'id_province'=>'19']);
        Canton::create(['name'=>'Pedro Moncayo', 'id_province'=>'19']);
        Canton::create(['name'=>'Cayambe', 'id_province'=>'19']);
        Canton::create(['name'=>'Rumiñahui', 'id_province'=>'19']);
        Canton::create(['name'=>'Mejia', 'id_province'=>'19']);
        Canton::create(['name'=>'La Concordia', 'id_province'=>'21']);
        Canton::create(['name'=>'Santo Domingo', 'id_province'=>'21']);
        Canton::create(['name'=>'Sucumbios', 'id_province'=>'22']);
        Canton::create(['name'=>'Gonzalo Pizarro', 'id_province'=>'22']);
        Canton::create(['name'=>'Cascales', 'id_province'=>'22']);
        Canton::create(['name'=>'Lago Agrio', 'id_province'=>'22']);
        Canton::create(['name'=>'Putumayo', 'id_province'=>'22']);
        Canton::create(['name'=>'Cuyabeno', 'id_province'=>'22']);
        Canton::create(['name'=>'Shushufindi', 'id_province'=>'22']);
        Canton::create(['name'=>'Chillanes', 'id_province'=>'23']);
        Canton::create(['name'=>'Ambato', 'id_province'=>'23']);
        Canton::create(['name'=>'Pillaro', 'id_province'=>'23']);
        Canton::create(['name'=>'Patate', 'id_province'=>'23']);
        Canton::create(['name'=>'Baños', 'id_province'=>'23']);
        Canton::create(['name'=>'Pelileo', 'id_province'=>'23']);
        Canton::create(['name'=>'Cevallos', 'id_province'=>'23']);
        Canton::create(['name'=>'Tisaleo', 'id_province'=>'23']);
        Canton::create(['name'=>'Mocha', 'id_province'=>'23']);
        Canton::create(['name'=>'Espindola', 'id_province'=>'24']);
        Canton::create(['name'=>'Yacuambi', 'id_province'=>'24']);
        Canton::create(['name'=>'Yantzaza', 'id_province'=>'24']);
        Canton::create(['name'=>'El Pangui', 'id_province'=>'24']);
        Canton::create(['name'=>'Zamora', 'id_province'=>'24']);
        Canton::create(['name'=>'Centinela del Condor', 'id_province'=>'24']);
        Canton::create(['name'=>'Paquisha', 'id_province'=>'24']);
        Canton::create(['name'=>'Nangaritza', 'id_province'=>'24']);
        Canton::create(['name'=>'Palanda', 'id_province'=>'24']);
        Canton::create(['name'=>'Balao',  'id_province'=>'20']);
        Canton::create(['name'=>'Santa Elena', 'id_province'=>'20']);
        Canton::create(['name'=>'La Libertad', 'id_province'=>'20']);
        
    }
} 
