<?php

namespace Database\Seeders;

use App\Models\Parish;
use Illuminate\Database\Seeder;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Parish::create(['name' => 'Cuenca', 'id_canton' => '48']);
        Parish::create(['name' => 'Giron', 'id_canton' => '69']);
        Parish::create(['name' => 'Gualaceo', 'id_canton' => '73']);
        Parish::create(['name' => 'Nabon', 'id_canton' => '117']);
        Parish::create(['name' => 'Paute', 'id_canton' => '140']);
        Parish::create(['name' => 'Pucara', 'id_canton' => '153']);
        Parish::create(['name' => 'San Fernando', 'id_canton' => '176']);
        Parish::create(['name' => 'Santa Isabel', 'id_canton' => '190']);
        Parish::create(['name' => 'Sigsig', 'id_canton' => '201']);
        Parish::create(['name' => 'San Felipe De Oña', 'id_canton' => '126']);
        Parish::create(['name' => 'Chordeleg', 'id_canton' => '42']);
        Parish::create(['name' => 'El Pan', 'id_canton' => '59']);
        Parish::create(['name' => 'Sevilla De Oro', 'id_canton' => '198']);
        Parish::create(['name' => 'Guachapala', 'id_canton' => '72']);
        Parish::create(['name' => 'Camilo Ponce Enriquez', 'id_canton' => '25']);
        Parish::create(['name' => 'Guaranda', 'id_canton' => '77']);
        Parish::create(['name' => 'Chillanes', 'id_canton' => '38']);
        Parish::create(['name' => 'San Jose De Chimbo', 'id_canton' => '39']);
        Parish::create(['name' => 'Echeandia', 'id_canton' => '54']);
        Parish::create(['name' => 'San Miguel', 'id_canton' => '180']);
        Parish::create(['name' => 'Caluma', 'id_canton' => '23']);
        Parish::create(['name' => 'Las Naves', 'id_canton' => '95']);
        Parish::create(['name' => 'Azogues', 'id_canton' => '12']);
        Parish::create(['name' => 'Biblian', 'id_canton' => '19']);
        Parish::create(['name' => 'Cañar', 'id_canton' => '31']);
        Parish::create(['name' => 'La Troncal', 'id_canton' => '92']);
        Parish::create(['name' => 'El Tambo', 'id_canton' => '61']);
        Parish::create(['name' => 'Deleg', 'id_canton' => '52']);
        Parish::create(['name' => 'Suscal', 'id_canton' => '207']);
        Parish::create(['name' => 'Tulcan', 'id_canton' => '212']);
        Parish::create(['name' => 'Bolivar', 'id_canton' => '21']);
        Parish::create(['name' => 'El Angel', 'id_canton' => '65']);
        Parish::create(['name' => 'Mira (Chontahuasi)', 'id_canton' => '109']);
        Parish::create(['name' => 'San Gabriel', 'id_canton' => '114']);
        Parish::create(['name' => 'Huaca', 'id_canton' => '183']);
        Parish::create(['name' => 'Latacunga', 'id_canton' => '96']);
        Parish::create(['name' => 'La Mana', 'id_canton' => '91']);
        Parish::create(['name' => 'El Corazon', 'id_canton' => '135']);
        Parish::create(['name' => 'Pujili', 'id_canton' => '157']);
        Parish::create(['name' => 'San Miguel', 'id_canton' => '171']);
        Parish::create(['name' => 'Saquisili,', 'id_canton' => '196']);
        Parish::create(['name' => 'Sigchos', 'id_canton' => '200']);
        Parish::create(['name' => 'Riobamba', 'id_canton' => '167']);
        Parish::create(['name' => 'Alausi', 'id_canton' => '3']);
        Parish::create(['name' => 'Villa La Union (Cajabamba)', 'id_canton' => '45']);
        Parish::create(['name' => 'Chambo', 'id_canton' => '36']);
        Parish::create(['name' => 'Chunchi', 'id_canton' => '43']);
        Parish::create(['name' => 'Guamote', 'id_canton' => '75']);
        Parish::create(['name' => 'Guano', 'id_canton' => '76']);
        Parish::create(['name' => 'Pallatanga', 'id_canton' => '132']);
        Parish::create(['name' => 'Penipe', 'id_canton' => '145']);
        Parish::create(['name' => 'Cumanda', 'id_canton' => '49']);
        Parish::create(['name' => 'Machala', 'id_canton' => '103']);
        Parish::create(['name' => 'Arenillas', 'id_canton' => '9']);
        Parish::create(['name' => 'Paccha', 'id_canton' => '11']);
        Parish::create(['name' => 'Balsas', 'id_canton' => '16']);
        Parish::create(['name' => 'Chilla', 'id_canton' => '37']);
        Parish::create(['name' => 'El Guabo', 'id_canton' => '58']);
        Parish::create(['name' => 'Huaquillas', 'id_canton' => '80']);
        Parish::create(['name' => 'Marcabeli', 'id_canton' => '105']);
        Parish::create(['name' => 'Pasaje', 'id_canton' => '137']);
        Parish::create(['name' => 'Piñas', 'id_canton' => '149']);
        Parish::create(['name' => 'Portovelo', 'id_canton' => '151']);
        Parish::create(['name' => 'Santa Rosa', 'id_canton' => '192']);
        Parish::create(['name' => 'Zaruma', 'id_canton' => '221']);
        Parish::create(['name' => 'La Victoria', 'id_canton' => '94']);
        Parish::create(['name' => 'Esmeraldas', 'id_canton' => '64']);
        Parish::create(['name' => 'Valdez (Limones)', 'id_canton' => '63']);
        Parish::create(['name' => 'Muisne', 'id_canton' => '116']);
        Parish::create(['name' => 'Rosa Zarate (Quininde)', 'id_canton' => '164']);
        Parish::create(['name' => 'San Lorenzo', 'id_canton' => '179']);
        Parish::create(['name' => 'Atacames', 'id_canton' => '10']);
        Parish::create(['name' => 'Rioverde', 'id_canton' => '168']);
        Parish::create(['name' => 'La Concordia', 'id_canton' => '88']);
        Parish::create(['name' => 'Guayaquil', 'id_canton' => '78']);
        Parish::create(['name' => 'Alfredo Baquerizo Moreno (Jujan)', 'id_canton' => '4']);
        Parish::create(['name' => 'Balao', 'id_canton' => '15']);
        Parish::create(['name' => 'Balzar', 'id_canton' => '17']);
        Parish::create(['name' => 'Colimes', 'id_canton' => '44']);
        Parish::create(['name' => 'Daule', 'id_canton' => '51']);
        Parish::create(['name' => 'Eloy Alfaro (Duran)', 'id_canton' => '53']);
        Parish::create(['name' => 'Velasco Ibarra (El Empalme)', 'id_canton' => '57']);
        Parish::create(['name' => 'El Triunfo', 'id_canton' => '62']);
        Parish::create(['name' => 'Milagro', 'id_canton' => '108']);
        Parish::create(['name' => 'Naranjal', 'id_canton' => '119']);
        Parish::create(['name' => 'Naranjito', 'id_canton' => '120']);
        Parish::create(['name' => 'Palestina', 'id_canton' => '131']);
        Parish::create(['name' => 'Pedro Carbo', 'id_canton' => '142']);
        Parish::create(['name' => 'Samborondon', 'id_canton' => '174']);
        Parish::create(['name' => 'Santa Lucia', 'id_canton' => '191']);
        Parish::create(['name' => 'El Salitre (Las Ramas)', 'id_canton' => '173']);
        Parish::create(['name' => 'San Jacinto De Yaguachi', 'id_canton' => '177']);
        Parish::create(['name' => 'General Villamil (Playas)', 'id_canton' => '150']);
        Parish::create(['name' => 'Simon Bolivar', 'id_canton' => '202']);
        Parish::create(['name' => 'Coronel Marcelino Maridueña (San Carlos)', 'id_canton' => '46']);
        Parish::create(['name' => 'Lomas De Sargentillo', 'id_canton' => '100']);
        Parish::create(['name' => 'Narcisa De Jesus', 'id_canton' => '121']);
        Parish::create(['name' => 'General Antonio Elizalde (Bucay)', 'id_canton' => '68']);
        Parish::create(['name' => 'Isidro Ayora', 'id_canton' => '83']);
        Parish::create(['name' => 'San Miguel De Ibarra', 'id_canton' => '81']);
        Parish::create(['name' => 'Atuntaqui', 'id_canton' => '6']);
        Parish::create(['name' => 'Cotacachi', 'id_canton' => '47']);
        Parish::create(['name' => 'Otavalo', 'id_canton' => '125']);
        Parish::create(['name' => 'Pimampiro', 'id_canton' => '147']);
        Parish::create(['name' => 'Urcuqui', 'id_canton' => '182']);
        Parish::create(['name' => 'Loja', 'id_canton' => '99']);
        Parish::create(['name' => 'Cariamanga', 'id_canton' => '24']);
        Parish::create(['name' => 'Catamayo (La Toma)', 'id_canton' => '29']);
        Parish::create(['name' => 'Celica', 'id_canton' => '32']);
        Parish::create(['name' => 'Chaguarpamba', 'id_canton' => '35']);
        Parish::create(['name' => 'Amaluza', 'id_canton' => '66']);
        Parish::create(['name' => 'Gonzanama', 'id_canton' => '71']);
        Parish::create(['name' => 'Macara', 'id_canton' => '102']);
        Parish::create(['name' => 'Catacocha', 'id_canton' => '134']);
        Parish::create(['name' => 'Alamor', 'id_canton' => '159']);
        Parish::create(['name' => 'Saraguro', 'id_canton' => '197']);
        Parish::create(['name' => 'Sozoranga', 'id_canton' => '203']);
        Parish::create(['name' => 'Zapotillo', 'id_canton' => '220']);
        Parish::create(['name' => 'Pindal', 'id_canton' => '148']);
        Parish::create(['name' => 'Quilanga', 'id_canton' => '163']);
        Parish::create(['name' => 'Olmedo', 'id_canton' => '122']);
        Parish::create(['name' => 'Babahoyo', 'id_canton' => '14']);
        Parish::create(['name' => 'Baba', 'id_canton' => '13']);
        Parish::create(['name' => 'Montalvo', 'id_canton' => '112']);
        Parish::create(['name' => 'Puebloviejo', 'id_canton' => '154']);
        Parish::create(['name' => 'Quevedo', 'id_canton' => '161']);
        Parish::create(['name' => 'Catarama', 'id_canton' => '213']);
        Parish::create(['name' => 'Ventanas', 'id_canton' => '215']);
        Parish::create(['name' => 'Vinces', 'id_canton' => '216']);
        Parish::create(['name' => 'Palenque', 'id_canton' => '130']);
        Parish::create(['name' => 'San Jacinto De Buena Fe', 'id_canton' => '22']);
        Parish::create(['name' => 'Valencia', 'id_canton' => '214']);
        Parish::create(['name' => 'Mocache', 'id_canton' => '110']);
        Parish::create(['name' => 'Quinsaloma', 'id_canton' => '165']);
        Parish::create(['name' => 'Portoviejo', 'id_canton' => '152']);
        Parish::create(['name' => 'Calceta', 'id_canton' => '20']);
        Parish::create(['name' => 'Chone', 'id_canton' => '41']);
        Parish::create(['name' => 'El Carmen', 'id_canton' => '55']);
        Parish::create(['name' => 'Flavio Alfaro', 'id_canton' => '67']);
        Parish::create(['name' => 'Jipijapa', 'id_canton' => '86']);
        Parish::create(['name' => 'Junin', 'id_canton' => '87']);
        Parish::create(['name' => 'Manta', 'id_canton' => '104']);
        Parish::create(['name' => 'Montecristi', 'id_canton' => '113']);
        Parish::create(['name' => 'Pajan', 'id_canton' => '128']);
        Parish::create(['name' => 'Pichincha', 'id_canton' => '146']);
        Parish::create(['name' => 'Rocafuerte', 'id_canton' => '169']);
        Parish::create(['name' => 'Santa Ana De Vuelta Larga', 'id_canton' => '186']);
        Parish::create(['name' => 'Bahia De Caraquez', 'id_canton' => '204']);
        Parish::create(['name' => 'Tosagua', 'id_canton' => '211']);
        Parish::create(['name' => 'Sucre', 'id_canton' => '1']);
        Parish::create(['name' => 'Pedernales', 'id_canton' => '141']);
        Parish::create(['name' => 'Olmedo', 'id_canton' => '123']);
        Parish::create(['name' => 'Puerto Lopez', 'id_canton' => '155']);
        Parish::create(['name' => 'Jama', 'id_canton' => '84']);
        Parish::create(['name' => 'Jaramijo', 'id_canton' => '85']);
        Parish::create(['name' => 'San Vicente', 'id_canton' => '185']);
        Parish::create(['name' => 'Macas', 'id_canton' => '115']);
        Parish::create(['name' => 'Gualaquiza', 'id_canton' => '74']);
        Parish::create(['name' => 'General Leonidas Plaza Gutierrez (Limon)', 'id_canton' => '97']);
        Parish::create(['name' => 'Palora (Metzera)', 'id_canton' => '133']);
        Parish::create(['name' => 'Santiago De Mendez', 'id_canton' => '193']);
        Parish::create(['name' => 'Sucua', 'id_canton' => '205']);
        Parish::create(['name' => 'Huamboya', 'id_canton' => '79']);
        Parish::create(['name' => 'San Juan Bosco', 'id_canton' => '178']);
        Parish::create(['name' => 'Taisha', 'id_canton' => '208']);
        Parish::create(['name' => 'Logroño', 'id_canton' => '98']);
        Parish::create(['name' => 'Pablo Sexto', 'id_canton' => '127']);
        Parish::create(['name' => 'Santiago', 'id_canton' => '26']);
        Parish::create(['name' => 'Tena', 'id_canton' => '209']);
        Parish::create(['name' => 'Archidona', 'id_canton' => '8']);
        Parish::create(['name' => 'El Chaco', 'id_canton' => '56']);
        Parish::create(['name' => 'Baeza', 'id_canton' => '162']);
        Parish::create(['name' => 'Carlos Julio Arosemena Tola', 'id_canton' => '27']);
        Parish::create(['name' => 'Puyo', 'id_canton' => '138']);
        Parish::create(['name' => 'Mera', 'id_canton' => '107']);
        Parish::create(['name' => 'Santa Clara', 'id_canton' => '187']);
        Parish::create(['name' => 'Arajuno', 'id_canton' => '7']);
        Parish::create(['name' => 'Quito Distrito Metropolitano, Cabecera Cantonal, Capital Provincial Y De La Republica Del Ecuador', 'id_canton' => '166']);
        Parish::create(['name' => 'Cayambe', 'id_canton' => '30']);
        Parish::create(['name' => 'Machachi', 'id_canton' => '106']);
        Parish::create(['name' => 'Tabacundo', 'id_canton' => '143']);
        Parish::create(['name' => 'Sangolqui', 'id_canton' => '170']);
        Parish::create(['name' => 'San Miguel De Los Bancos', 'id_canton' => '181']);
        Parish::create(['name' => 'Pedro Vicente Maldonado', 'id_canton' => '144']);
        Parish::create(['name' => 'Puerto Quito', 'id_canton' => '156']);
        Parish::create(['name' => 'Ambato', 'id_canton' => '5']);
        Parish::create(['name' => 'Baños De Agua Santa', 'id_canton' => '18']);
        Parish::create(['name' => 'Cevallos', 'id_canton' => '34']);
        Parish::create(['name' => 'Mocha', 'id_canton' => '111']);
        Parish::create(['name' => 'Patate', 'id_canton' => '139']);
        Parish::create(['name' => 'Quero', 'id_canton' => '160']);
        Parish::create(['name' => 'Pelileo', 'id_canton' => '184']);
        Parish::create(['name' => 'Pillaro', 'id_canton' => '194']);
        Parish::create(['name' => 'Tisaleo', 'id_canton' => '210']);
        Parish::create(['name' => 'Zamora', 'id_canton' => '219']);
        Parish::create(['name' => 'Zumba', 'id_canton' => '40']);
        Parish::create(['name' => 'Guayzimi', 'id_canton' => '118']);
        Parish::create(['name' => '28 De Mayo (San Jose De Yacuambi)', 'id_canton' => '217']);
        Parish::create(['name' => 'Yantzaza (Yanzatza)', 'id_canton' => '218']);
        Parish::create(['name' => 'El Pangui', 'id_canton' => '60']);
        Parish::create(['name' => 'Zumbi', 'id_canton' => '33']);
        Parish::create(['name' => 'Palanda', 'id_canton' => '129']);
        Parish::create(['name' => 'Paquisha', 'id_canton' => '136']);
        Parish::create(['name' => 'Puerto Baquerizo Moreno', 'id_canton' => '175']);
        Parish::create(['name' => 'Puerto Villamil', 'id_canton' => '82']);
        Parish::create(['name' => 'Puerto Ayora', 'id_canton' => '188']);
        Parish::create(['name' => 'Nueva Loja', 'id_canton' => '93']);
        Parish::create(['name' => 'Lumbaqui', 'id_canton' => '70']);
        Parish::create(['name' => 'Puerto El Carmen Del Putumayo', 'id_canton' => '158']);
        Parish::create(['name' => 'Shushufindi', 'id_canton' => '199']);
        Parish::create(['name' => 'La Bonita', 'id_canton' => '206']);
        Parish::create(['name' => 'El Dorado De Cascales', 'id_canton' => '28']);
        Parish::create(['name' => 'Tarapoa', 'id_canton' => '50']);
        Parish::create(['name' => 'Puerto Francisco De Orellana (El Coca)', 'id_canton' => '124']);
        Parish::create(['name' => 'Nuevo Rocafuerte', 'id_canton' => '2']);
        Parish::create(['name' => 'La Joya De Los Sachas', 'id_canton' => '89']);
        Parish::create(['name' => 'Loreto', 'id_canton' => '101']);
        Parish::create(['name' => 'Asuncion', 'id_canton' => '69']);
        Parish::create(['name' => 'Cochapata', 'id_canton' => '117']);
        Parish::create(['name' => 'Chumblin', 'id_canton' => '176']);
        Parish::create(['name' => 'Abdon Calderon (La Union)', 'id_canton' => '190']);
        Parish::create(['name' => 'Cuchil (Cutchil)', 'id_canton' => '201']);
        Parish::create(['name' => 'Susudel', 'id_canton' => '126']);
        Parish::create(['name' => 'Principal', 'id_canton' => '42']);
        Parish::create(['name' => 'Amaluza', 'id_canton' => '198']);
        Parish::create(['name' => 'San Jose Del Tambo (Tambopamba)', 'id_canton' => '38']);
        Parish::create(['name' => 'Asuncion (Asancoto)', 'id_canton' => '39']);
        Parish::create(['name' => 'Balsapamba', 'id_canton' => '180']);
        Parish::create(['name' => 'Nazon (Cab. En Pampa De Dominguez)', 'id_canton' => '19']);
        Parish::create(['name' => 'Chontamarca', 'id_canton' => '31']);
        Parish::create(['name' => 'Manuel J. Calle', 'id_canton' => '92']);
        Parish::create(['name' => 'Solano', 'id_canton' => '52']);
        Parish::create(['name' => 'Garcia Moreno', 'id_canton' => '21']);
        Parish::create(['name' => 'El Goaltal', 'id_canton' => '65']);
        Parish::create(['name' => 'Concepcion', 'id_canton' => '109']);
        Parish::create(['name' => 'Cristobal Colon', 'id_canton' => '114']);
        Parish::create(['name' => 'Mariscal Sucre', 'id_canton' => '183']);
        Parish::create(['name' => 'Guasaganda (Cab.En Guasaganda Centro)', 'id_canton' => '91']);
        Parish::create(['name' => 'Moraspungo', 'id_canton' => '135']);
        Parish::create(['name' => 'Angamarca', 'id_canton' => '157']);
        Parish::create(['name' => 'Antonio Jose Holguin (Santa Lucia)', 'id_canton' => '171']);
        Parish::create(['name' => 'Canchagua', 'id_canton' => '196']);
        Parish::create(['name' => 'Chugchillan', 'id_canton' => '200']);
        Parish::create(['name' => 'Achupallas', 'id_canton' => '3']);
        Parish::create(['name' => 'Cañi', 'id_canton' => '45']);
        Parish::create(['name' => 'Capzol', 'id_canton' => '43']);
        Parish::create(['name' => 'Cebadas', 'id_canton' => '75']);
        Parish::create(['name' => 'Guanando', 'id_canton' => '76']);
        Parish::create(['name' => 'El Altar', 'id_canton' => '145']);
        Parish::create(['name' => 'Chacras', 'id_canton' => '9']);
        Parish::create(['name' => 'Ayapamba', 'id_canton' => '11']);
        Parish::create(['name' => 'Bellamaria', 'id_canton' => '16']);
        Parish::create(['name' => 'Barbones (Sucre)', 'id_canton' => '58']);
        Parish::create(['name' => 'El Ingenio', 'id_canton' => '105']);
        Parish::create(['name' => 'Buenavista', 'id_canton' => '137']);
        Parish::create(['name' => 'Capiro (Cab. En La Capilla De Capiro)', 'id_canton' => '149']);
        Parish::create(['name' => 'Curtincapa', 'id_canton' => '151']);
        Parish::create(['name' => 'Bellavista', 'id_canton' => '192']);
        Parish::create(['name' => 'Abañin', 'id_canton' => '221']);
        Parish::create(['name' => 'La Libertad', 'id_canton' => '94']);
        Parish::create(['name' => 'Anchayacu', 'id_canton' => '63']);
        Parish::create(['name' => 'Bolivar', 'id_canton' => '116']);
        Parish::create(['name' => 'Cube', 'id_canton' => '164']);
        Parish::create(['name' => 'Alto Tambo (Cab. En Guadual)', 'id_canton' => '179']);
        Parish::create(['name' => 'La Union', 'id_canton' => '10']);
        Parish::create(['name' => 'Chontaduro', 'id_canton' => '168']);
        Parish::create(['name' => 'San Jacinto', 'id_canton' => '44']);
        Parish::create(['name' => 'Guayas (Pueblo Nuevo)', 'id_canton' => '57']);
        Parish::create(['name' => 'Chobo', 'id_canton' => '108']);
        Parish::create(['name' => 'Jesus Maria', 'id_canton' => '119']);
        Parish::create(['name' => 'Valle De La Virgen', 'id_canton' => '142']);
        Parish::create(['name' => 'Tarifa', 'id_canton' => '174']);
        Parish::create(['name' => 'Gral. Vernaza (Dos Esteros)', 'id_canton' => '173']);
        Parish::create(['name' => 'Crnel.Lorenzo De Garaicoa (Pedregal)', 'id_canton' => '202']);
        Parish::create(['name' => 'Imbaya (San Luis De Cobuendo)', 'id_canton' => '6']);
        Parish::create(['name' => 'Apuela', 'id_canton' => '47']);
        Parish::create(['name' => 'Dr. Miguel Egas Cabezas (Peguche)', 'id_canton' => '125']);
        Parish::create(['name' => 'Chuga', 'id_canton' => '147']);
        Parish::create(['name' => 'Cahuasqui', 'id_canton' => '182']);
        Parish::create(['name' => 'Colaisaca', 'id_canton' => '24']);
        Parish::create(['name' => 'El Tambo', 'id_canton' => '29']);
        Parish::create(['name' => 'Cruzpamba (Cab. En Carlos Bustamante)', 'id_canton' => '32']);
        Parish::create(['name' => 'Buenavista', 'id_canton' => '35']);
        Parish::create(['name' => 'Bellavista', 'id_canton' => '66']);
        Parish::create(['name' => 'Changaimina (La Libertad)', 'id_canton' => '71']);
        Parish::create(['name' => 'Larama', 'id_canton' => '102']);
        Parish::create(['name' => 'Cangonama', 'id_canton' => '134']);
        Parish::create(['name' => 'Ciano', 'id_canton' => '159']);
        Parish::create(['name' => 'El Paraiso De Celen', 'id_canton' => '197']);
        Parish::create(['name' => 'Nueva Fatima', 'id_canton' => '203']);
        Parish::create(['name' => 'Cazaderos (Cab.En Mangaurco)', 'id_canton' => '220']);
        Parish::create(['name' => 'Chaquinal', 'id_canton' => '148']);
        Parish::create(['name' => 'Fundochamba', 'id_canton' => '163']);
        Parish::create(['name' => 'La Tingue', 'id_canton' => '122']);
        Parish::create(['name' => 'Guare', 'id_canton' => '13']);
        Parish::create(['name' => 'Puerto Pechiche', 'id_canton' => '154']);
        Parish::create(['name' => 'Ricaurte', 'id_canton' => '213']);
        Parish::create(['name' => 'Antonio Sotomayor (Cab. En Playas De Vinces)', 'id_canton' => '216']);
        Parish::create(['name' => 'Patricia Pilar', 'id_canton' => '22']);
        Parish::create(['name' => 'Membrillo', 'id_canton' => '20']);
        Parish::create(['name' => 'Boyaca', 'id_canton' => '41']);
        Parish::create(['name' => 'Wilfrido Loor Moreira (Maicito)', 'id_canton' => '55']);
        Parish::create(['name' => 'San Francisco De Novillo (Cab. En Novillo)', 'id_canton' => '67']);
        Parish::create(['name' => 'America', 'id_canton' => '86']);
        Parish::create(['name' => 'San Lorenzo', 'id_canton' => '104']);
        Parish::create(['name' => 'Campozano (La Palma De Pajan)', 'id_canton' => '128']);
        Parish::create(['name' => 'Barraganete', 'id_canton' => '146']);
        Parish::create(['name' => 'Ayacucho', 'id_canton' => '186']);
        Parish::create(['name' => 'Bachillero', 'id_canton' => '211']);
        Parish::create(['name' => 'Bellavista', 'id_canton' => '1']);
        Parish::create(['name' => 'Cojimies', 'id_canton' => '141']);
        Parish::create(['name' => 'Machalilla', 'id_canton' => '155']);
        Parish::create(['name' => 'Canoa', 'id_canton' => '185']);
        Parish::create(['name' => 'Amazonas (Rosario De Cuyes)', 'id_canton' => '74']);
        Parish::create(['name' => 'Indanza', 'id_canton' => '97']);
        Parish::create(['name' => 'Arapicos', 'id_canton' => '133']);
        Parish::create(['name' => 'Copal', 'id_canton' => '193']);
        Parish::create(['name' => 'Asuncion', 'id_canton' => '205']);
        Parish::create(['name' => 'Chiguaza', 'id_canton' => '79']);
        Parish::create(['name' => 'Pan De Azucar', 'id_canton' => '178']);
        Parish::create(['name' => 'Huasaga (Cab. En Wampuik)', 'id_canton' => '208']);
        Parish::create(['name' => 'Yaupi', 'id_canton' => '98']);
        Parish::create(['name' => 'San Jose De Morona', 'id_canton' => '26']);
        Parish::create(['name' => 'Gonzalo Diaz De Pineda (El Bombon)', 'id_canton' => '56']);
        Parish::create(['name' => 'Cosanga', 'id_canton' => '162']);
        Parish::create(['name' => 'Madre Tierra', 'id_canton' => '107']);
        Parish::create(['name' => 'San Jose', 'id_canton' => '187']);
        Parish::create(['name' => 'Curaray', 'id_canton' => '7']);
        Parish::create(['name' => 'Ascazubi', 'id_canton' => '30']);
        Parish::create(['name' => 'Aloag', 'id_canton' => '106']);
        Parish::create(['name' => 'La Esperanza', 'id_canton' => '143']);
        Parish::create(['name' => 'Cotogchoa', 'id_canton' => '170']);
        Parish::create(['name' => 'Mindo', 'id_canton' => '181']);
        Parish::create(['name' => 'Lligua', 'id_canton' => '18']);
        Parish::create(['name' => 'Pinguili', 'id_canton' => '111']);
        Parish::create(['name' => 'El Triunfo', 'id_canton' => '139']);
        Parish::create(['name' => 'Rumipamba', 'id_canton' => '160']);
        Parish::create(['name' => 'Benitez (Pachanlica)', 'id_canton' => '184']);
        Parish::create(['name' => 'Baquerizo Moreno', 'id_canton' => '194']);
        Parish::create(['name' => 'Quinchicoto', 'id_canton' => '210']);
        Parish::create(['name' => 'Chito', 'id_canton' => '40']);
        Parish::create(['name' => 'Zurmi', 'id_canton' => '118']);
        Parish::create(['name' => 'La Paz', 'id_canton' => '217']);
        Parish::create(['name' => 'Chicaña', 'id_canton' => '218']);
        Parish::create(['name' => 'El Guisme', 'id_canton' => '60']);
        Parish::create(['name' => 'El Porvenir Del Carmen', 'id_canton' => '129']);
        Parish::create(['name' => 'Bellavista', 'id_canton' => '136']);
        Parish::create(['name' => 'Tomas De Berlanga (Santo Tomas)', 'id_canton' => '82']);
        Parish::create(['name' => 'Bellavista', 'id_canton' => '188']);
        Parish::create(['name' => 'El Reventador', 'id_canton' => '70']);
        Parish::create(['name' => 'Palma Roja', 'id_canton' => '158']);
        Parish::create(['name' => 'Limoncocha', 'id_canton' => '199']);
        Parish::create(['name' => 'El Playon De San Francisco', 'id_canton' => '206']);
        Parish::create(['name' => 'Santa Rosa De Sucumbios', 'id_canton' => '28']);
        Parish::create(['name' => 'Cuyabeno', 'id_canton' => '50']);
        Parish::create(['name' => 'Capitan Augusto Rivadeneyra', 'id_canton' => '2']);
        Parish::create(['name' => 'Enokanqui', 'id_canton' => '89']);
        Parish::create(['name' => 'Avila (Cab. En Huiruno)', 'id_canton' => '101']);
        Parish::create(['name' => 'San Gerardo', 'id_canton' => '69']);
        Parish::create(['name' => 'Daniel Cordova Toral (El Oriente)', 'id_canton' => '73']);
        Parish::create(['name' => 'El Progreso (Cab.En Zhota)', 'id_canton' => '117']);
        Parish::create(['name' => 'Bulan (Jose Victor Izquierdo)', 'id_canton' => '140']);
        Parish::create(['name' => 'San Rafael De Sharug', 'id_canton' => '153']);
        Parish::create(['name' => 'El Carmen De Pijili', 'id_canton' => '190']);
        Parish::create(['name' => 'Jima (Gima)', 'id_canton' => '201']);
        Parish::create(['name' => 'La Union', 'id_canton' => '42']);
        Parish::create(['name' => 'Palmas', 'id_canton' => '198']);
        Parish::create(['name' => 'Bilovan', 'id_canton' => '180']);
        Parish::create(['name' => 'San Francisco De Sageo', 'id_canton' => '19']);
        Parish::create(['name' => 'Chorocopte', 'id_canton' => '31']);
        Parish::create(['name' => 'Pancho Negro', 'id_canton' => '92']);
        Parish::create(['name' => 'Los Andes', 'id_canton' => '21']);
        Parish::create(['name' => 'La Libertad (Alizo)', 'id_canton' => '65']);
        Parish::create(['name' => 'Jijon Y Caamaño (Cab. En Rio Blanco)', 'id_canton' => '109']);
        Parish::create(['name' => 'Chitan De Navarrete', 'id_canton' => '114']);
        Parish::create(['name' => 'Pucayacu', 'id_canton' => '91']);
        Parish::create(['name' => 'Pinllopata', 'id_canton' => '135']);
        Parish::create(['name' => 'Cusubamba', 'id_canton' => '171']);
        Parish::create(['name' => 'Chantilin', 'id_canton' => '196']);
        Parish::create(['name' => 'Isinlivi', 'id_canton' => '200']);
        Parish::create(['name' => 'Columbe', 'id_canton' => '45']);
        Parish::create(['name' => 'Compud', 'id_canton' => '43']);
        Parish::create(['name' => 'Palmira', 'id_canton' => '75']);
        Parish::create(['name' => 'Ilapo', 'id_canton' => '76']);
        Parish::create(['name' => 'Matus', 'id_canton' => '145']);
        Parish::create(['name' => 'Cordoncillo', 'id_canton' => '11']);
        Parish::create(['name' => 'La Iberia', 'id_canton' => '58']);
        Parish::create(['name' => 'Casacay', 'id_canton' => '137']);
        Parish::create(['name' => 'La Bocana', 'id_canton' => '149']);
        Parish::create(['name' => 'Morales', 'id_canton' => '151']);
        Parish::create(['name' => 'Jambeli', 'id_canton' => '192']);
        Parish::create(['name' => 'Arcapamba', 'id_canton' => '221']);
        Parish::create(['name' => 'El Paraiso', 'id_canton' => '94']);
        Parish::create(['name' => 'Atahualpa (Cab. En Camarones)', 'id_canton' => '63']);
        Parish::create(['name' => 'Daule', 'id_canton' => '116']);
        Parish::create(['name' => 'Chura (Chancama) (Cab. En El Yerbero)', 'id_canton' => '164']);
        Parish::create(['name' => 'Ancon (Pichangal) (Cab. En Palma Real)', 'id_canton' => '179']);
        Parish::create(['name' => 'Sua (Cab. En La Bocana)', 'id_canton' => '10']);
        Parish::create(['name' => 'Chumunde', 'id_canton' => '168']);
        Parish::create(['name' => 'Juan Bautista Aguirre (Los Tintos)', 'id_canton' => '51']);
        Parish::create(['name' => 'El Rosario', 'id_canton' => '57']);
        Parish::create(['name' => 'San Carlos', 'id_canton' => '119']);
        Parish::create(['name' => 'Sabanilla', 'id_canton' => '142']);
        Parish::create(['name' => 'La Victoria (Ñauza)', 'id_canton' => '173']);
        Parish::create(['name' => 'San Francisco De Natabuela', 'id_canton' => '6']);
        Parish::create(['name' => 'Garcia Moreno (Llurimagua)', 'id_canton' => '47']);
        Parish::create(['name' => 'Eugenio Espejo (Calpaqui)', 'id_canton' => '125']);
        Parish::create(['name' => 'Mariano Acosta', 'id_canton' => '147']);
        Parish::create(['name' => 'La Merced De Buenos Aires', 'id_canton' => '182']);
        Parish::create(['name' => 'El Lucero', 'id_canton' => '24']);
        Parish::create(['name' => 'Guayquichuma', 'id_canton' => '29']);
        Parish::create(['name' => 'El Rosario', 'id_canton' => '35']);
        Parish::create(['name' => 'Jimbura', 'id_canton' => '66']);
        Parish::create(['name' => 'La Victoria', 'id_canton' => '102']);
        Parish::create(['name' => 'Guachanama', 'id_canton' => '134']);
        Parish::create(['name' => 'El Arenal', 'id_canton' => '159']);
        Parish::create(['name' => 'El Tablon', 'id_canton' => '197']);
        Parish::create(['name' => 'Tacamoros', 'id_canton' => '203']);
        Parish::create(['name' => 'Garzareal', 'id_canton' => '220']);
        Parish::create(['name' => '12 De Diciembre (Cab.En Achiotes)', 'id_canton' => '148']);
        Parish::create(['name' => 'San Antonio De Las Aradas (Cab. En Las Aradas)', 'id_canton' => '163']);
        Parish::create(['name' => 'Isla De Bejucal', 'id_canton' => '13']);
        Parish::create(['name' => 'San Juan', 'id_canton' => '154']);
        Parish::create(['name' => 'Zapotal', 'id_canton' => '215']);
        Parish::create(['name' => 'Quiroga', 'id_canton' => '20']);
        Parish::create(['name' => 'Canuto', 'id_canton' => '41']);
        Parish::create(['name' => 'San Pedro De Suma', 'id_canton' => '55']);
        Parish::create(['name' => 'Zapallo', 'id_canton' => '67']);
        Parish::create(['name' => 'El Anegado (Cab. En Eloy Alfaro)', 'id_canton' => '86']);
        Parish::create(['name' => 'Santa Marianita (Boca De Pacoche)', 'id_canton' => '104']);
        Parish::create(['name' => 'La Pila', 'id_canton' => '113']);
        Parish::create(['name' => 'Cascol', 'id_canton' => '128']);
        Parish::create(['name' => 'San Sebastian', 'id_canton' => '146']);
        Parish::create(['name' => 'Honorato Vasquez (Cab. En Vasquez)', 'id_canton' => '186']);
        Parish::create(['name' => 'Angel Pedro Giler (La Estancilla)', 'id_canton' => '211']);
        Parish::create(['name' => 'Noboa', 'id_canton' => '1']);
        Parish::create(['name' => '10 De Agosto', 'id_canton' => '141']);
        Parish::create(['name' => 'Salango', 'id_canton' => '155']);
        Parish::create(['name' => 'Bermejos', 'id_canton' => '74']);
        Parish::create(['name' => 'Cumanda (Cab. En Colonia Agricola Sevilla Del Oro)', 'id_canton' => '133']);
        Parish::create(['name' => 'Chupianza', 'id_canton' => '193']);
        Parish::create(['name' => 'Huambi', 'id_canton' => '205']);
        Parish::create(['name' => 'San Carlos De Limon', 'id_canton' => '178']);
        Parish::create(['name' => 'Macuma', 'id_canton' => '208']);
        Parish::create(['name' => 'Shimpis', 'id_canton' => '98']);
        Parish::create(['name' => 'Cotundo', 'id_canton' => '8']);
        Parish::create(['name' => 'Linares', 'id_canton' => '56']);
        Parish::create(['name' => 'Cuyuja', 'id_canton' => '162']);
        Parish::create(['name' => 'Shell', 'id_canton' => '107']);
        Parish::create(['name' => 'Cangahua', 'id_canton' => '30']);
        Parish::create(['name' => 'Aloasi', 'id_canton' => '106']);
        Parish::create(['name' => 'Malchingui', 'id_canton' => '143']);
        Parish::create(['name' => 'Rumipamba', 'id_canton' => '170']);
        Parish::create(['name' => 'Rio Negro', 'id_canton' => '18']);
        Parish::create(['name' => 'Los Andes (Cab. En Poatug)', 'id_canton' => '139']);
        Parish::create(['name' => 'Yanayacu - Mochapata (Cab. En Yanayacu)', 'id_canton' => '160']);
        Parish::create(['name' => 'Bolivar', 'id_canton' => '184']);
        Parish::create(['name' => 'Emilio Maria Teran (Rumipamba)', 'id_canton' => '194']);
        Parish::create(['name' => 'El Chorro', 'id_canton' => '40']);
        Parish::create(['name' => 'Nuevo Paraiso', 'id_canton' => '118']);
        Parish::create(['name' => 'Tutupali', 'id_canton' => '217']);
        Parish::create(['name' => 'Pachicutza', 'id_canton' => '60']);
        Parish::create(['name' => 'San Francisco Del Vergel', 'id_canton' => '129']);
        Parish::create(['name' => 'Nuevo Quito', 'id_canton' => '136']);
        Parish::create(['name' => 'Santa Rosa (Incluye La Isla Baltra)', 'id_canton' => '188']);
        Parish::create(['name' => 'Gonzalo Pizarro', 'id_canton' => '70']);
        Parish::create(['name' => 'Puerto Bolivar (Puerto Montufar)', 'id_canton' => '158']);
        Parish::create(['name' => 'Pañacocha', 'id_canton' => '199']);
        Parish::create(['name' => 'La Sofia', 'id_canton' => '206']);
        Parish::create(['name' => 'Sevilla', 'id_canton' => '28']);
        Parish::create(['name' => 'Aguas Negras', 'id_canton' => '50']);
        Parish::create(['name' => 'Cononaco', 'id_canton' => '2']);
        Parish::create(['name' => 'Pompeya', 'id_canton' => '89']);
        Parish::create(['name' => 'Puerto Murialdo', 'id_canton' => '101']);
        Parish::create(['name' => 'Jadan', 'id_canton' => '73']);
        Parish::create(['name' => 'Las Nieves (Chaya)', 'id_canton' => '117']);
        Parish::create(['name' => 'Chican (Guillermo Ortega)', 'id_canton' => '140']);
        Parish::create(['name' => 'Zhaglli (Shaglli)', 'id_canton' => '190']);
        Parish::create(['name' => 'Guel', 'id_canton' => '201']);
        Parish::create(['name' => 'Luis Galarza Orellana (Cab.En Delegsol)', 'id_canton' => '42']);
        Parish::create(['name' => 'San Vicente', 'id_canton' => '59']);
        Parish::create(['name' => 'Magdalena (Chapacoto)', 'id_canton' => '39']);
        Parish::create(['name' => 'Regulo De Mora', 'id_canton' => '180']);
        Parish::create(['name' => 'Turupamba', 'id_canton' => '19']);
        Parish::create(['name' => 'General Morales (Socarte)', 'id_canton' => '31']);
        Parish::create(['name' => 'Monte Olivo', 'id_canton' => '21']);
        Parish::create(['name' => 'San Isidro', 'id_canton' => '65']);
        Parish::create(['name' => 'Juan Montalvo (San Ignacio De Quil)', 'id_canton' => '109']);
        Parish::create(['name' => 'Fernandez Salvador', 'id_canton' => '114']);
        Parish::create(['name' => 'Ramon Campaña', 'id_canton' => '135']);
        Parish::create(['name' => 'Guangaje', 'id_canton' => '157']);
        Parish::create(['name' => 'Mulalillo', 'id_canton' => '171']);
        Parish::create(['name' => 'Cochapamba', 'id_canton' => '196']);
        Parish::create(['name' => 'Las Pampas', 'id_canton' => '200']);
        Parish::create(['name' => 'Guasuntos', 'id_canton' => '3']);
        Parish::create(['name' => 'Juan De Velasco (Pangor)', 'id_canton' => '45']);
        Parish::create(['name' => 'Gonzol', 'id_canton' => '43']);
        Parish::create(['name' => 'La Providencia', 'id_canton' => '76']);
        Parish::create(['name' => 'Puela', 'id_canton' => '145']);
        Parish::create(['name' => 'Milagro', 'id_canton' => '11']);
        Parish::create(['name' => 'Tendales (Cab.En Puerto Tendales)', 'id_canton' => '58']);
        Parish::create(['name' => 'La Peaña', 'id_canton' => '137']);
        Parish::create(['name' => 'Moromoro (Cab. En El Vado)', 'id_canton' => '149']);
        Parish::create(['name' => 'Salati', 'id_canton' => '151']);
        Parish::create(['name' => 'La Avanzada', 'id_canton' => '192']);
        Parish::create(['name' => 'Guanazan', 'id_canton' => '221']);
        Parish::create(['name' => 'San Isidro', 'id_canton' => '94']);
        Parish::create(['name' => 'Borbon', 'id_canton' => '63']);
        Parish::create(['name' => 'Galera', 'id_canton' => '116']);
        Parish::create(['name' => 'Malimpia', 'id_canton' => '164']);
        Parish::create(['name' => 'Calderon', 'id_canton' => '179']);
        Parish::create(['name' => 'Tonchigüe', 'id_canton' => '10']);
        Parish::create(['name' => 'Lagarto', 'id_canton' => '168']);
        Parish::create(['name' => 'Laurel', 'id_canton' => '51']);
        Parish::create(['name' => 'Mariscal Sucre (Huaques)', 'id_canton' => '108']);
        Parish::create(['name' => 'Santa Rosa De Flandes', 'id_canton' => '119']);
        Parish::create(['name' => 'Junquillal', 'id_canton' => '173']);
        Parish::create(['name' => 'Gral. Pedro J. Montero (Boliche)', 'id_canton' => '177']);
        Parish::create(['name' => 'San Jose De Chaltura', 'id_canton' => '6']);
        Parish::create(['name' => 'Imantag', 'id_canton' => '47']);
        Parish::create(['name' => 'Gonzalez Suarez', 'id_canton' => '125']);
        Parish::create(['name' => 'San Francisco De Sigsipamba', 'id_canton' => '147']);
        Parish::create(['name' => 'Pablo Arenas', 'id_canton' => '182']);
        Parish::create(['name' => 'Utuana', 'id_canton' => '24']);
        Parish::create(['name' => 'San Pedro De La Bendita', 'id_canton' => '29']);
        Parish::create(['name' => 'Santa Rufina', 'id_canton' => '35']);
        Parish::create(['name' => 'Santa Teresita', 'id_canton' => '66']);
        Parish::create(['name' => 'Nambacola', 'id_canton' => '71']);
        Parish::create(['name' => 'Sabiango (La Capilla)', 'id_canton' => '102']);
        Parish::create(['name' => 'El Limo (Mariana De Jesus)', 'id_canton' => '159']);
        Parish::create(['name' => 'Lluzhapa', 'id_canton' => '197']);
        Parish::create(['name' => 'Limones', 'id_canton' => '220']);
        Parish::create(['name' => 'San Carlos', 'id_canton' => '161']);
        Parish::create(['name' => 'Convento', 'id_canton' => '41']);
        Parish::create(['name' => 'Julcuy', 'id_canton' => '86']);
        Parish::create(['name' => 'Guale', 'id_canton' => '128']);
        Parish::create(['name' => 'La Union', 'id_canton' => '186']);
        Parish::create(['name' => 'Charapoto', 'id_canton' => '204']);
        Parish::create(['name' => 'Arq. Sixto Duran Ballen', 'id_canton' => '1']);
        Parish::create(['name' => 'Atahualpa', 'id_canton' => '141']);
        Parish::create(['name' => 'Bomboiza', 'id_canton' => '74']);
        Parish::create(['name' => 'San Antonio (Cab. En San Antonio Centro', 'id_canton' => '97']);
        Parish::create(['name' => 'Patuca', 'id_canton' => '193']);
        Parish::create(['name' => 'San Jacinto De Wakambeis', 'id_canton' => '178']);
        Parish::create(['name' => 'Tuutinentza', 'id_canton' => '208']);
        Parish::create(['name' => 'Oyacachi', 'id_canton' => '56']);
        Parish::create(['name' => 'Papallacta', 'id_canton' => '162']);
        Parish::create(['name' => 'Olmedo (Pesillo)', 'id_canton' => '30']);
        Parish::create(['name' => 'Cutuglahua', 'id_canton' => '106']);
        Parish::create(['name' => 'Tocachi', 'id_canton' => '143']);
        Parish::create(['name' => 'Rio Verde', 'id_canton' => '18']);
        Parish::create(['name' => 'Sucre (Cab. En Sucre-Patate Urcu)', 'id_canton' => '139']);
        Parish::create(['name' => 'Cotalo', 'id_canton' => '184']);
        Parish::create(['name' => 'Marcos Espinel (Chacata)', 'id_canton' => '194']);
        Parish::create(['name' => 'Los Encuentros', 'id_canton' => '218']);
        Parish::create(['name' => 'Tundayme', 'id_canton' => '60']);
        Parish::create(['name' => 'Valladolid', 'id_canton' => '129']);
        Parish::create(['name' => 'Puerto Rodriguez', 'id_canton' => '158']);
        Parish::create(['name' => 'San Roque (Cab. En San Vicente)', 'id_canton' => '199']);
        Parish::create(['name' => 'Rosa Florida', 'id_canton' => '206']);
        Parish::create(['name' => 'Santa Maria De Huiririma', 'id_canton' => '2']);
        Parish::create(['name' => 'San Carlos', 'id_canton' => '89']);
        Parish::create(['name' => 'San Jose De Payamino', 'id_canton' => '101']);
        Parish::create(['name' => 'Mariano Moreno', 'id_canton' => '73']);
        Parish::create(['name' => 'El Cabo', 'id_canton' => '140']);
        Parish::create(['name' => 'Ludo', 'id_canton' => '201']);
        Parish::create(['name' => 'San Martin De Puzhio', 'id_canton' => '42']);
        Parish::create(['name' => 'San Sebastian', 'id_canton' => '39']);
        Parish::create(['name' => 'San Pablo (San Pablo De Atenas)', 'id_canton' => '180']);
        Parish::create(['name' => 'Jerusalen', 'id_canton' => '19']);
        Parish::create(['name' => 'Gualleturo', 'id_canton' => '31']);
        Parish::create(['name' => 'San Vicente De Pusir', 'id_canton' => '21']);
        Parish::create(['name' => 'La Paz', 'id_canton' => '114']);
        Parish::create(['name' => 'Mulliquindil (Santa Ana)', 'id_canton' => '171']);
        Parish::create(['name' => 'Palo Quemado', 'id_canton' => '200']);
        Parish::create(['name' => 'Huigra', 'id_canton' => '3']);
        Parish::create(['name' => 'Santiago De Quito (Cab. En San Antonio De Quito)', 'id_canton' => '45']);
        Parish::create(['name' => 'Llagos', 'id_canton' => '43']);
        Parish::create(['name' => 'San Andres', 'id_canton' => '76']);
        Parish::create(['name' => 'San Antonio De Bayushig', 'id_canton' => '145']);
        Parish::create(['name' => 'Palmales', 'id_canton' => '9']);
        Parish::create(['name' => 'San Jose', 'id_canton' => '11']);
        Parish::create(['name' => 'Rio Bonito', 'id_canton' => '58']);
        Parish::create(['name' => 'Progreso', 'id_canton' => '137']);
        Parish::create(['name' => 'Piedras', 'id_canton' => '149']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '192']);
        Parish::create(['name' => 'Guizhaguiña', 'id_canton' => '221']);
        Parish::create(['name' => 'La Tola', 'id_canton' => '63']);
        Parish::create(['name' => 'Quingue (Olmedo Perdomo Franco)', 'id_canton' => '116']);
        Parish::create(['name' => 'Viche', 'id_canton' => '164']);
        Parish::create(['name' => 'Carondelet', 'id_canton' => '179']);
        Parish::create(['name' => 'Tonsupa', 'id_canton' => '10']);
        Parish::create(['name' => 'Montalvo (Cab. En Horqueta)', 'id_canton' => '168']);
        Parish::create(['name' => 'Limonal', 'id_canton' => '51']);
        Parish::create(['name' => 'Roberto Astudillo (Cab. En Cruce De Venecia)', 'id_canton' => '108']);
        Parish::create(['name' => 'Taura', 'id_canton' => '119']);
        Parish::create(['name' => 'San Roque', 'id_canton' => '6']);
        Parish::create(['name' => 'Peñaherrera', 'id_canton' => '47']);
        Parish::create(['name' => 'Pataqui', 'id_canton' => '125']);
        Parish::create(['name' => 'San Blas', 'id_canton' => '182']);
        Parish::create(['name' => 'Sanguillin', 'id_canton' => '24']);
        Parish::create(['name' => 'Zambi', 'id_canton' => '29']);
        Parish::create(['name' => 'Amarillos', 'id_canton' => '35']);
        Parish::create(['name' => '27 De Abril (Cab. En La Naranja)', 'id_canton' => '66']);
        Parish::create(['name' => 'Purunuma (Eguiguren)', 'id_canton' => '71']);
        Parish::create(['name' => 'Lauro Guerrero', 'id_canton' => '134']);
        Parish::create(['name' => 'Mercadillo', 'id_canton' => '159']);
        Parish::create(['name' => 'Manu', 'id_canton' => '197']);
        Parish::create(['name' => 'Paletillas', 'id_canton' => '220']);
        Parish::create(['name' => 'Chibunga', 'id_canton' => '41']);
        Parish::create(['name' => 'La Union', 'id_canton' => '86']);
        Parish::create(['name' => 'Lascano', 'id_canton' => '128']);
        Parish::create(['name' => 'Chigüinda', 'id_canton' => '74']);
        Parish::create(['name' => 'Sangay (Cab. En Nayamanaca)', 'id_canton' => '133']);
        Parish::create(['name' => 'San Luis De El Acho (Cab. En El Acho)', 'id_canton' => '193']);
        Parish::create(['name' => 'Santiago De Pananza', 'id_canton' => '178']);
        Parish::create(['name' => 'Pumpuentsa', 'id_canton' => '208']);
        Parish::create(['name' => 'San Pablo De Ushpayacu', 'id_canton' => '8']);
        Parish::create(['name' => 'Santa Rosa', 'id_canton' => '56']);
        Parish::create(['name' => 'San Francisco De Borja (Virgilio Davila)', 'id_canton' => '162']);
        Parish::create(['name' => 'Oton', 'id_canton' => '30']);
        Parish::create(['name' => 'El Chaupi', 'id_canton' => '106']);
        Parish::create(['name' => 'Tupigachi', 'id_canton' => '143']);
        Parish::create(['name' => 'Ulba', 'id_canton' => '18']);
        Parish::create(['name' => 'Chiquicha (Cab. En Chiquicha Grande)', 'id_canton' => '184']);
        Parish::create(['name' => 'Presidente Urbina (Chagrapamba -Patzucul)', 'id_canton' => '194']);
        Parish::create(['name' => 'La Chonta', 'id_canton' => '40']);
        Parish::create(['name' => 'La Canela', 'id_canton' => '129']);
        Parish::create(['name' => 'Puerto Libre', 'id_canton' => '70']);
        Parish::create(['name' => 'Santa Elena', 'id_canton' => '158']);
        Parish::create(['name' => 'San Pedro De Los Cofanes', 'id_canton' => '199']);
        Parish::create(['name' => 'Santa Barbara', 'id_canton' => '206']);
        Parish::create(['name' => 'Tiputini', 'id_canton' => '2']);
        Parish::create(['name' => 'San Sebastian Del Coca', 'id_canton' => '89']);
        Parish::create(['name' => 'Remigio Crespo Toral (Gulag)', 'id_canton' => '73']);
        Parish::create(['name' => 'San Juan', 'id_canton' => '73']);
        Parish::create(['name' => 'Zhidmad', 'id_canton' => '73']);
        Parish::create(['name' => 'Luis Cordero Vega', 'id_canton' => '73']);
        Parish::create(['name' => 'Simon Bolivar (Cab. En Gañanzol)', 'id_canton' => '73']);
        Parish::create(['name' => 'Guarainag', 'id_canton' => '140']);
        Parish::create(['name' => 'San Cristobal (Carlos Ordoñez Lazo)', 'id_canton' => '140']);
        Parish::create(['name' => 'Tomebamba', 'id_canton' => '140']);
        Parish::create(['name' => 'Dug Dug', 'id_canton' => '140']);
        Parish::create(['name' => 'San Bartolome', 'id_canton' => '201']);
        Parish::create(['name' => 'San Jose De Raranga', 'id_canton' => '201']);
        Parish::create(['name' => 'Telimbela', 'id_canton' => '39']);
        Parish::create(['name' => 'Santiago', 'id_canton' => '180']);
        Parish::create(['name' => 'San Vicente', 'id_canton' => '180']);
        Parish::create(['name' => 'Honorato Vasquez (Tambo Viejo)', 'id_canton' => '31']);
        Parish::create(['name' => 'Ingapirca', 'id_canton' => '31']);
        Parish::create(['name' => 'Juncal', 'id_canton' => '31']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '31']);
        Parish::create(['name' => 'Zhud', 'id_canton' => '31']);
        Parish::create(['name' => 'Ventura', 'id_canton' => '31']);
        Parish::create(['name' => 'Ducur', 'id_canton' => '31']);
        Parish::create(['name' => 'San Rafael', 'id_canton' => '21']);
        Parish::create(['name' => 'Piartal', 'id_canton' => '114']);
        Parish::create(['name' => 'La Victoria', 'id_canton' => '157']);
        Parish::create(['name' => 'Pilalo', 'id_canton' => '157']);
        Parish::create(['name' => 'Tingo', 'id_canton' => '157']);
        Parish::create(['name' => 'Zumbahua', 'id_canton' => '157']);
        Parish::create(['name' => 'Pansaleo', 'id_canton' => '171']);
        Parish::create(['name' => 'Multitud', 'id_canton' => '3']);
        Parish::create(['name' => 'Pistishi (Nariz Del Diablo)', 'id_canton' => '3']);
        Parish::create(['name' => 'Pumallacta', 'id_canton' => '3']);
        Parish::create(['name' => 'Sevilla', 'id_canton' => '3']);
        Parish::create(['name' => 'Sibambe', 'id_canton' => '3']);
        Parish::create(['name' => 'Tixan', 'id_canton' => '3']);
        Parish::create(['name' => 'San Gerardo De Pacaicaguan', 'id_canton' => '76']);
        Parish::create(['name' => 'San Isidro De Patulu', 'id_canton' => '76']);
        Parish::create(['name' => 'San Jose Del Chazo', 'id_canton' => '76']);
        Parish::create(['name' => 'Santa Fe De Galan', 'id_canton' => '76']);
        Parish::create(['name' => 'Valparaiso', 'id_canton' => '76']);
        Parish::create(['name' => 'La Candelaria', 'id_canton' => '145']);
        Parish::create(['name' => 'Bilbao (Cab.En Quilluyacu)', 'id_canton' => '145']);
        Parish::create(['name' => 'Carcabon', 'id_canton' => '9']);
        Parish::create(['name' => 'San Juan De Cerro Azul', 'id_canton' => '11']);
        Parish::create(['name' => 'Uzhcurrumi', 'id_canton' => '137']);
        Parish::create(['name' => 'Cañaquemada', 'id_canton' => '137']);
        Parish::create(['name' => 'San Roque (Ambrosio Maldonado)', 'id_canton' => '149']);
        Parish::create(['name' => 'Saracay', 'id_canton' => '149']);
        Parish::create(['name' => 'Torata', 'id_canton' => '192']);
        Parish::create(['name' => 'Victoria', 'id_canton' => '192']);
        Parish::create(['name' => 'Bellamaria', 'id_canton' => '192']);
        Parish::create(['name' => 'Huertas', 'id_canton' => '221']);
        Parish::create(['name' => 'Malvas', 'id_canton' => '221']);
        Parish::create(['name' => 'Muluncay Grande', 'id_canton' => '221']);
        Parish::create(['name' => 'Sinsao', 'id_canton' => '221']);
        Parish::create(['name' => 'Salvias', 'id_canton' => '221']);
        Parish::create(['name' => 'Luis Vargas Torres (Cab. En Playa De Oro)', 'id_canton' => '63']);
        Parish::create(['name' => 'Maldonado', 'id_canton' => '63']);
        Parish::create(['name' => 'Pampanal De Bolivar', 'id_canton' => '63']);
        Parish::create(['name' => 'San Francisco De Onzole', 'id_canton' => '63']);
        Parish::create(['name' => 'Santo Domingo De Onzole', 'id_canton' => '63']);
        Parish::create(['name' => 'Selva Alegre', 'id_canton' => '63']);
        Parish::create(['name' => 'Telembi', 'id_canton' => '63']);
        Parish::create(['name' => 'Colon Eloy Del Maria', 'id_canton' => '63']);
        Parish::create(['name' => 'San Jose De Cayapas', 'id_canton' => '63']);
        Parish::create(['name' => 'Timbire', 'id_canton' => '63']);
        Parish::create(['name' => 'Salima', 'id_canton' => '116']);
        Parish::create(['name' => 'San Francisco', 'id_canton' => '116']);
        Parish::create(['name' => 'San Gregorio', 'id_canton' => '116']);
        Parish::create(['name' => 'San Jose De Chamanga (Cab.En Chamanga)', 'id_canton' => '116']);
        Parish::create(['name' => 'La Union', 'id_canton' => '164']);
        Parish::create(['name' => '5 De Junio (Cab. En Uimbi)', 'id_canton' => '179']);
        Parish::create(['name' => 'Concepcion', 'id_canton' => '179']);
        Parish::create(['name' => 'Mataje (Cab. En Santander)', 'id_canton' => '179']);
        Parish::create(['name' => 'San Javier De Cachavi (Cab. En San Javier)', 'id_canton' => '179']);
        Parish::create(['name' => 'Santa Rita', 'id_canton' => '179']);
        Parish::create(['name' => 'Tambillo', 'id_canton' => '179']);
        Parish::create(['name' => 'Tululbi (Cab. En Ricaurte)', 'id_canton' => '179']);
        Parish::create(['name' => 'Urbina', 'id_canton' => '179']);
        Parish::create(['name' => 'Rocafuerte', 'id_canton' => '168']);
        Parish::create(['name' => 'Los Lojas (Enrique Baquerizo Moreno)', 'id_canton' => '51']);
        Parish::create(['name' => 'Yaguachi Viejo (Cone)', 'id_canton' => '177']);
        Parish::create(['name' => 'Virgen De Fatima', 'id_canton' => '177']);
        Parish::create(['name' => 'Plaza Gutierrez', 'id_canton' => '47']);
        Parish::create(['name' => 'Quiroga', 'id_canton' => '47']);
        Parish::create(['name' => '6 De Julio De Cuellaje (Cab. En Cuellaje)', 'id_canton' => '47']);
        Parish::create(['name' => 'Vacas Galindo (El Churo) (Cab.En San Miguel Alto)', 'id_canton' => '47']);
        Parish::create(['name' => 'San Jose De Quichinche', 'id_canton' => '125']);
        Parish::create(['name' => 'San Juan De Iluman', 'id_canton' => '125']);
        Parish::create(['name' => 'San Pablo', 'id_canton' => '125']);
        Parish::create(['name' => 'San Rafael', 'id_canton' => '125']);
        Parish::create(['name' => 'Selva Alegre (Cab.En San Miguel De Pamplona)', 'id_canton' => '125']);
        Parish::create(['name' => 'Tumbabiro', 'id_canton' => '182']);
        Parish::create(['name' => 'Pozul (San Juan De Pozul)', 'id_canton' => '32']);
        Parish::create(['name' => 'Sabanilla', 'id_canton' => '32']);
        Parish::create(['name' => 'Tnte. Maximiliano Rodriguez Loaiza', 'id_canton' => '32']);
        Parish::create(['name' => 'El Ingenio', 'id_canton' => '66']);
        Parish::create(['name' => 'El Airo', 'id_canton' => '66']);
        Parish::create(['name' => 'Sacapalca', 'id_canton' => '71']);
        Parish::create(['name' => 'Orianga', 'id_canton' => '134']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '134']);
        Parish::create(['name' => 'Casanga', 'id_canton' => '134']);
        Parish::create(['name' => 'Yamana', 'id_canton' => '134']);
        Parish::create(['name' => 'Vicentino', 'id_canton' => '159']);
        Parish::create(['name' => 'San Antonio De Qumbe (Cumbe)', 'id_canton' => '197']);
        Parish::create(['name' => 'San Pablo De Tenta', 'id_canton' => '197']);
        Parish::create(['name' => 'San Sebastian De Yuluc', 'id_canton' => '197']);
        Parish::create(['name' => 'Selva Alegre', 'id_canton' => '197']);
        Parish::create(['name' => 'Urdaneta (Paquishapa)', 'id_canton' => '197']);
        Parish::create(['name' => 'Sumaypamba', 'id_canton' => '197']);
        Parish::create(['name' => 'Bolaspamba', 'id_canton' => '220']);
        Parish::create(['name' => 'La Esperanza', 'id_canton' => '161']);
        Parish::create(['name' => 'Eloy Alfaro', 'id_canton' => '41']);
        Parish::create(['name' => 'Ricaurte', 'id_canton' => '41']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '41']);
        Parish::create(['name' => 'Membrillal', 'id_canton' => '86']);
        Parish::create(['name' => 'Pedro Pablo Gomez', 'id_canton' => '86']);
        Parish::create(['name' => 'Puerto De Cayo', 'id_canton' => '86']);
        Parish::create(['name' => 'San Pablo (Cab. En Pueblo Nuevo)', 'id_canton' => '186']);
        Parish::create(['name' => 'San Isidro', 'id_canton' => '204']);
        Parish::create(['name' => 'El Rosario', 'id_canton' => '74']);
        Parish::create(['name' => 'Nueva Tarqui', 'id_canton' => '74']);
        Parish::create(['name' => 'San Miguel De Cuyes', 'id_canton' => '74']);
        Parish::create(['name' => 'El Ideal', 'id_canton' => '74']);
        Parish::create(['name' => 'San Miguel De Conchay', 'id_canton' => '97']);
        Parish::create(['name' => 'Santa Susana De Chiviaza (Cab. En Chiviaza)', 'id_canton' => '97']);
        Parish::create(['name' => 'Yunganza (Cab. En El Rosario)', 'id_canton' => '97']);
        Parish::create(['name' => '16 De Agosto', 'id_canton' => '133']);
        Parish::create(['name' => 'Tayuza', 'id_canton' => '193']);
        Parish::create(['name' => 'San Francisco De Chinimbimi', 'id_canton' => '193']);
        Parish::create(['name' => 'Santa Marianita De Jesus', 'id_canton' => '205']);
        Parish::create(['name' => 'Sardinas', 'id_canton' => '56']);
        Parish::create(['name' => 'Sumaco', 'id_canton' => '162']);
        Parish::create(['name' => 'Santa Rosa De Cuzubamba', 'id_canton' => '30']);
        Parish::create(['name' => 'Manuel Cornejo Astorga (Tandapi)', 'id_canton' => '106']);
        Parish::create(['name' => 'Tambillo', 'id_canton' => '106']);
        Parish::create(['name' => 'Uyumbicho', 'id_canton' => '106']);
        Parish::create(['name' => 'El Rosario (Rumichaca)', 'id_canton' => '184']);
        Parish::create(['name' => 'Garcia Moreno (Chumaqui)', 'id_canton' => '184']);
        Parish::create(['name' => 'Guambalo (Huambalo)', 'id_canton' => '184']);
        Parish::create(['name' => 'Salasaca', 'id_canton' => '184']);
        Parish::create(['name' => 'San Andres', 'id_canton' => '194']);
        Parish::create(['name' => 'San Jose De Poalo', 'id_canton' => '194']);
        Parish::create(['name' => 'San Miguelito', 'id_canton' => '194']);
        Parish::create(['name' => 'Pucapamba', 'id_canton' => '40']);
        Parish::create(['name' => 'San Andres', 'id_canton' => '40']);
        Parish::create(['name' => 'Siete De Julio', 'id_canton' => '199']);
        Parish::create(['name' => 'Yasuni', 'id_canton' => '2']);
        Parish::create(['name' => 'Lago San Pedro', 'id_canton' => '89']);
        Parish::create(['name' => 'Rumipamba', 'id_canton' => '89']);
        Parish::create(['name' => 'Tres De Noviembre', 'id_canton' => '89']);
        Parish::create(['name' => 'Union Milagreña', 'id_canton' => '89']);
        Parish::create(['name' => 'Baños', 'id_canton' => '48']);
        Parish::create(['name' => 'Cumbe', 'id_canton' => '48']);
        Parish::create(['name' => 'Chaucha', 'id_canton' => '48']);
        Parish::create(['name' => 'Checa (Jidcay)', 'id_canton' => '48']);
        Parish::create(['name' => 'Chiquintad', 'id_canton' => '48']);
        Parish::create(['name' => 'Llacao', 'id_canton' => '48']);
        Parish::create(['name' => 'Molleturo', 'id_canton' => '48']);
        Parish::create(['name' => 'Nulti', 'id_canton' => '48']);
        Parish::create(['name' => 'Octavio Cordero Palacios (Santa Rosa)', 'id_canton' => '48']);
        Parish::create(['name' => 'Paccha', 'id_canton' => '48']);
        Parish::create(['name' => 'Quingeo', 'id_canton' => '48']);
        Parish::create(['name' => 'Ricaurte', 'id_canton' => '48']);
        Parish::create(['name' => 'San Joaquin', 'id_canton' => '48']);
        Parish::create(['name' => 'Santa Ana', 'id_canton' => '48']);
        Parish::create(['name' => 'Sayausi', 'id_canton' => '48']);
        Parish::create(['name' => 'Sidcay', 'id_canton' => '48']);
        Parish::create(['name' => 'Sinincay', 'id_canton' => '48']);
        Parish::create(['name' => 'Tarqui', 'id_canton' => '48']);
        Parish::create(['name' => 'Turi', 'id_canton' => '48']);
        Parish::create(['name' => 'Valle', 'id_canton' => '48']);
        Parish::create(['name' => 'Victoria Del Portete (Irquis)', 'id_canton' => '48']);
        Parish::create(['name' => 'Facundo Vela', 'id_canton' => '77']);
        Parish::create(['name' => 'Julio E. Moreno (Catanahuan Grande)', 'id_canton' => '77']);
        Parish::create(['name' => 'Salinas', 'id_canton' => '77']);
        Parish::create(['name' => 'San Lorenzo', 'id_canton' => '77']);
        Parish::create(['name' => 'San Simon (Yacoto)', 'id_canton' => '77']);
        Parish::create(['name' => 'Santafe (Santa Fe)', 'id_canton' => '77']);
        Parish::create(['name' => 'Simiatug', 'id_canton' => '77']);
        Parish::create(['name' => 'San Luis De Pambil', 'id_canton' => '77']);
        Parish::create(['name' => 'Cojitambo', 'id_canton' => '12']);
        Parish::create(['name' => 'Guapan', 'id_canton' => '12']);
        Parish::create(['name' => 'Javier Loyola (Chuquipata)', 'id_canton' => '12']);
        Parish::create(['name' => 'Luis Cordero', 'id_canton' => '12']);
        Parish::create(['name' => 'Pindilig', 'id_canton' => '12']);
        Parish::create(['name' => 'Rivera', 'id_canton' => '12']);
        Parish::create(['name' => 'San Miguel', 'id_canton' => '12']);
        Parish::create(['name' => 'Taday', 'id_canton' => '12']);
        Parish::create(['name' => 'El Carmelo (El Pun)', 'id_canton' => '212']);
        Parish::create(['name' => 'Julio Andrade (Orejuela)', 'id_canton' => '212']);
        Parish::create(['name' => 'Maldonado', 'id_canton' => '212']);
        Parish::create(['name' => 'Pioter', 'id_canton' => '212']);
        Parish::create(['name' => 'Tobar Donoso (La Bocana De Camumbi)', 'id_canton' => '212']);
        Parish::create(['name' => 'Tufiño', 'id_canton' => '212']);
        Parish::create(['name' => 'Urbina (Taya)', 'id_canton' => '212']);
        Parish::create(['name' => 'El Chical', 'id_canton' => '212']);
        Parish::create(['name' => 'Santa Martha De Cuba', 'id_canton' => '212']);
        Parish::create(['name' => 'Alaques (Alaquez)', 'id_canton' => '96']);
        Parish::create(['name' => 'Belisario Quevedo (Guanailin)', 'id_canton' => '96']);
        Parish::create(['name' => 'Guaitacama (Guaytacama)', 'id_canton' => '96']);
        Parish::create(['name' => 'Joseguango Bajo', 'id_canton' => '96']);
        Parish::create(['name' => 'Mulalo', 'id_canton' => '96']);
        Parish::create(['name' => '11 De Noviembre (Ilinchisi)', 'id_canton' => '96']);
        Parish::create(['name' => 'Poalo', 'id_canton' => '96']);
        Parish::create(['name' => 'San Juan De Pastocalle', 'id_canton' => '96']);
        Parish::create(['name' => 'Tanicuchi', 'id_canton' => '96']);
        Parish::create(['name' => 'Toacaso', 'id_canton' => '96']);
        Parish::create(['name' => 'Cacha (Cab. En Machangara)', 'id_canton' => '167']);
        Parish::create(['name' => 'Calpi', 'id_canton' => '167']);
        Parish::create(['name' => 'Cubijies', 'id_canton' => '167']);
        Parish::create(['name' => 'Flores', 'id_canton' => '167']);
        Parish::create(['name' => 'Lican', 'id_canton' => '167']);
        Parish::create(['name' => 'Licto', 'id_canton' => '167']);
        Parish::create(['name' => 'Pungala', 'id_canton' => '167']);
        Parish::create(['name' => 'Punin', 'id_canton' => '167']);
        Parish::create(['name' => 'Quimiag', 'id_canton' => '167']);
        Parish::create(['name' => 'San Juan', 'id_canton' => '167']);
        Parish::create(['name' => 'San Luis', 'id_canton' => '167']);
        Parish::create(['name' => 'El Retiro', 'id_canton' => '103']);
        Parish::create(['name' => 'Camarones (Cab. En San Vicente)', 'id_canton' => '64']);
        Parish::create(['name' => 'Crnel. Carlos Concha Torres (Cab.En Huele)', 'id_canton' => '64']);
        Parish::create(['name' => 'Chinca', 'id_canton' => '64']);
        Parish::create(['name' => 'Majua', 'id_canton' => '64']);
        Parish::create(['name' => 'San Mateo', 'id_canton' => '64']);
        Parish::create(['name' => 'Tabiazo', 'id_canton' => '64']);
        Parish::create(['name' => 'Tachina', 'id_canton' => '64']);
        Parish::create(['name' => 'Vuelta Larga', 'id_canton' => '64']);
        Parish::create(['name' => 'Juan Gomez Rendon (Progreso)', 'id_canton' => '78']);
        Parish::create(['name' => 'Morro', 'id_canton' => '78']);
        Parish::create(['name' => 'Posorja', 'id_canton' => '78']);
        Parish::create(['name' => 'Puna', 'id_canton' => '78']);
        Parish::create(['name' => 'Tenguel', 'id_canton' => '78']);
        Parish::create(['name' => 'Ambuqui', 'id_canton' => '81']);
        Parish::create(['name' => 'Angochagua', 'id_canton' => '81']);
        Parish::create(['name' => 'Carolina', 'id_canton' => '81']);
        Parish::create(['name' => 'La Esperanza', 'id_canton' => '81']);
        Parish::create(['name' => 'Lita', 'id_canton' => '81']);
        Parish::create(['name' => 'Salinas', 'id_canton' => '81']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '81']);
        Parish::create(['name' => 'Chantaco', 'id_canton' => '99']);
        Parish::create(['name' => 'Chuquiribamba', 'id_canton' => '99']);
        Parish::create(['name' => 'El Cisne', 'id_canton' => '99']);
        Parish::create(['name' => 'Gualel', 'id_canton' => '99']);
        Parish::create(['name' => 'Jimbilla', 'id_canton' => '99']);
        Parish::create(['name' => 'Malacatos (Valladolid)', 'id_canton' => '99']);
        Parish::create(['name' => 'San Lucas', 'id_canton' => '99']);
        Parish::create(['name' => 'San Pedro De Vilcabamba', 'id_canton' => '99']);
        Parish::create(['name' => 'Santiago', 'id_canton' => '99']);
        Parish::create(['name' => 'Taquil (Miguel Riofrio)', 'id_canton' => '99']);
        Parish::create(['name' => 'Vilcabamba (Victoria)', 'id_canton' => '99']);
        Parish::create(['name' => 'Yangana (Arsenio Castillo)', 'id_canton' => '99']);
        Parish::create(['name' => 'Quinara', 'id_canton' => '99']);
        Parish::create(['name' => 'Caracol', 'id_canton' => '14']);
        Parish::create(['name' => 'Febres Cordero (Las Juntas) (Cab. En Mata De Cacao)', 'id_canton' => '14']);
        Parish::create(['name' => 'Pimocha', 'id_canton' => '14']);
        Parish::create(['name' => 'La Union', 'id_canton' => '14']);
        Parish::create(['name' => 'Abdon Calderon (San Francisco)', 'id_canton' => '152']);
        Parish::create(['name' => 'Alhajuela (Bajo Grande)', 'id_canton' => '152']);
        Parish::create(['name' => 'Crucita', 'id_canton' => '152']);
        Parish::create(['name' => 'Pueblo Nuevo', 'id_canton' => '152']);
        Parish::create(['name' => 'Riochico (Rio Chico)', 'id_canton' => '152']);
        Parish::create(['name' => 'San Placido', 'id_canton' => '152']);
        Parish::create(['name' => 'Chirijos', 'id_canton' => '152']);
        Parish::create(['name' => 'Alshi (Cab. En 9 De Octubre)', 'id_canton' => '115']);
        Parish::create(['name' => 'General Proaño', 'id_canton' => '115']);
        Parish::create(['name' => 'San Isidro', 'id_canton' => '115']);
        Parish::create(['name' => 'Sevilla Don Bosco', 'id_canton' => '115']);
        Parish::create(['name' => 'Sinai', 'id_canton' => '115']);
        Parish::create(['name' => 'Zuña (Zuñac)', 'id_canton' => '115']);
        Parish::create(['name' => 'Cuchaentza', 'id_canton' => '115']);
        Parish::create(['name' => 'Rio Blanco', 'id_canton' => '115']);
        Parish::create(['name' => 'Ahuano', 'id_canton' => '209']);
        Parish::create(['name' => 'Chontapunta', 'id_canton' => '209']);
        Parish::create(['name' => 'Pano', 'id_canton' => '209']);
        Parish::create(['name' => 'Puerto Misahualli', 'id_canton' => '209']);
        Parish::create(['name' => 'Puerto Napo', 'id_canton' => '209']);
        Parish::create(['name' => 'Talag', 'id_canton' => '209']);
        Parish::create(['name' => 'Canelos', 'id_canton' => '138']);
        Parish::create(['name' => 'Diez De Agosto', 'id_canton' => '138']);
        Parish::create(['name' => 'Fatima', 'id_canton' => '138']);
        Parish::create(['name' => 'Montalvo (Andoas)', 'id_canton' => '138']);
        Parish::create(['name' => 'Pomona', 'id_canton' => '138']);
        Parish::create(['name' => 'Rio Corrientes', 'id_canton' => '138']);
        Parish::create(['name' => 'Rio Tigre', 'id_canton' => '138']);
        Parish::create(['name' => 'Sarayacu', 'id_canton' => '138']);
        Parish::create(['name' => 'Simon Bolivar (Cab. En Mushullacta)', 'id_canton' => '138']);
        Parish::create(['name' => 'Tarqui', 'id_canton' => '138']);
        Parish::create(['name' => 'Teniente Hugo Ortiz', 'id_canton' => '138']);
        Parish::create(['name' => 'Veracruz (Indillama) (Cab. En Indillama)', 'id_canton' => '138']);
        Parish::create(['name' => 'El Triunfo', 'id_canton' => '138']);
        Parish::create(['name' => 'Alangasi', 'id_canton' => '166']);
        Parish::create(['name' => 'Amaguaña', 'id_canton' => '166']);
        Parish::create(['name' => 'Atahualpa (Habaspamba)', 'id_canton' => '166']);
        Parish::create(['name' => 'Calacali', 'id_canton' => '166']);
        Parish::create(['name' => 'Calderon (Carapungo)', 'id_canton' => '166']);
        Parish::create(['name' => 'Conocoto', 'id_canton' => '166']);
        Parish::create(['name' => 'Cumbaya', 'id_canton' => '166']);
        Parish::create(['name' => 'Chavezpamba', 'id_canton' => '166']);
        Parish::create(['name' => 'Checa (Chilpa)', 'id_canton' => '166']);
        Parish::create(['name' => 'El Quinche', 'id_canton' => '166']);
        Parish::create(['name' => 'Gualea', 'id_canton' => '166']);
        Parish::create(['name' => 'Guangopolo', 'id_canton' => '166']);
        Parish::create(['name' => 'Guayllabamba', 'id_canton' => '166']);
        Parish::create(['name' => 'La Merced', 'id_canton' => '166']);
        Parish::create(['name' => 'Llano Chico', 'id_canton' => '166']);
        Parish::create(['name' => 'Lloa', 'id_canton' => '166']);
        Parish::create(['name' => 'Nanegal', 'id_canton' => '166']);
        Parish::create(['name' => 'Nanegalito', 'id_canton' => '166']);
        Parish::create(['name' => 'Nayon', 'id_canton' => '166']);
        Parish::create(['name' => 'Nono', 'id_canton' => '166']);
        Parish::create(['name' => 'Pacto', 'id_canton' => '166']);
        Parish::create(['name' => 'Perucho', 'id_canton' => '166']);
        Parish::create(['name' => 'Pifo', 'id_canton' => '166']);
        Parish::create(['name' => 'Pintag', 'id_canton' => '166']);
        Parish::create(['name' => 'Pomasqui', 'id_canton' => '166']);
        Parish::create(['name' => 'Puellaro', 'id_canton' => '166']);
        Parish::create(['name' => 'Puembo', 'id_canton' => '166']);
        Parish::create(['name' => 'San Antonio', 'id_canton' => '166']);
        Parish::create(['name' => 'San Jose De Minas', 'id_canton' => '166']);
        Parish::create(['name' => 'Tababela', 'id_canton' => '166']);
        Parish::create(['name' => 'Tumbaco', 'id_canton' => '166']);
        Parish::create(['name' => 'Yaruqui', 'id_canton' => '166']);
        Parish::create(['name' => 'Zambiza', 'id_canton' => '166']);
        Parish::create(['name' => 'Ambatillo', 'id_canton' => '5']);
        Parish::create(['name' => 'Atahualpa (Chisalata)', 'id_canton' => '5']);
        Parish::create(['name' => 'Augusto N. Martinez (Mundugleo)', 'id_canton' => '5']);
        Parish::create(['name' => 'Constantino Fernandez (Cab. En Cullitahua)', 'id_canton' => '5']);
        Parish::create(['name' => 'Huachi Grande', 'id_canton' => '5']);
        Parish::create(['name' => 'Izamba', 'id_canton' => '5']);
        Parish::create(['name' => 'Juan Benigno Vela', 'id_canton' => '5']);
        Parish::create(['name' => 'Montalvo', 'id_canton' => '5']);
        Parish::create(['name' => 'Pasa', 'id_canton' => '5']);
        Parish::create(['name' => 'Picaigua', 'id_canton' => '5']);
        Parish::create(['name' => 'Pilagüin (Pilahüin)', 'id_canton' => '5']);
        Parish::create(['name' => 'Quisapincha (Quizapincha)', 'id_canton' => '5']);
        Parish::create(['name' => 'San Bartolome De Pinllog', 'id_canton' => '5']);
        Parish::create(['name' => 'San Fernando (Pasa San Fernando)', 'id_canton' => '5']);
        Parish::create(['name' => 'Santa Rosa', 'id_canton' => '5']);
        Parish::create(['name' => 'Totoras', 'id_canton' => '5']);
        Parish::create(['name' => 'Cunchibamba', 'id_canton' => '5']);
        Parish::create(['name' => 'Unamuncho', 'id_canton' => '5']);
        Parish::create(['name' => 'Cumbaratza', 'id_canton' => '219']);
        Parish::create(['name' => 'Guadalupe', 'id_canton' => '219']);
        Parish::create(['name' => 'Imbana (La Victoria De Imbana)', 'id_canton' => '219']);
        Parish::create(['name' => 'Sabanilla', 'id_canton' => '219']);
        Parish::create(['name' => 'Timbara', 'id_canton' => '219']);
        Parish::create(['name' => 'San Carlos De Las Minas', 'id_canton' => '219']);
        Parish::create(['name' => 'El Progreso', 'id_canton' => '175']);
        Parish::create(['name' => 'Isla Santa Maria (Floreana) (Cab. En Pto. Velasco Ibarra)', 'id_canton' => '175']);
        Parish::create(['name' => 'Dureno', 'id_canton' => '93']);
        Parish::create(['name' => 'General Farfan', 'id_canton' => '93']);
        Parish::create(['name' => 'El Eno', 'id_canton' => '93']);
        Parish::create(['name' => 'Pacayacu', 'id_canton' => '93']);
        Parish::create(['name' => 'Jambeli', 'id_canton' => '93']);
        Parish::create(['name' => 'Santa Cecilia', 'id_canton' => '93']);
        Parish::create(['name' => 'Dayuma', 'id_canton' => '124']);
        Parish::create(['name' => 'Taracoa (Cab. En Nueva Esperanza: Yuca)', 'id_canton' => '124']);
        Parish::create(['name' => 'Alejandro Labaka', 'id_canton' => '124']);
        Parish::create(['name' => 'El Dorado', 'id_canton' => '124']);
        Parish::create(['name' => 'El Eden', 'id_canton' => '124']);
        Parish::create(['name' => 'Garcia Moreno', 'id_canton' => '124']);
        Parish::create(['name' => 'Ines Arango (Cab. En Western)', 'id_canton' => '124']);
        Parish::create(['name' => 'La Belleza', 'id_canton' => '124']);
        Parish::create(['name' => 'Nuevo Paraiso (Cab. En Unión Chimborazo)', 'id_canton' => '124']);
        Parish::create(['name' => 'San Jose De Guayusa', 'id_canton' => '124']);
        Parish::create(['name' => 'San Luis De Armenia', 'id_canton' => '124']);
    }
}
