<?php

namespace Database\Seeders;

use App\Models\Race;
use Illuminate\Database\Seeder;

class RaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Race::create(['name' => 'Affenpinscher', 'id_specie' => '1']); 
        Race::create(['name' => 'Airedale Terrier', 'id_specie' => '1']); 
        Race::create(['name' => 'Akita Americano', 'id_specie' => '1']); 
        Race::create(['name' => 'Akita Inu', 'id_specie' => '1']); 
        Race::create(['name' => 'Alaskan Malamute', 'id_specie' => '1']); 
        Race::create(['name' => 'American Staffordshire Terrier', 'id_specie' => '1']); 
        Race::create(['name' => 'Antiguo perro de muestra danés', 'id_specie' => '1']); 
        Race::create(['name' => 'Azawakh', 'id_specie' => '1']); 
        Race::create(['name' => 'Azul de Gascuña', 'id_specie' => '1']); 
        Race::create(['name' => 'Basenji', 'id_specie' => '1']);
        Race::create(['name' => 'Basset artesiano de Normandía', 'id_specie' => '1']);
        Race::create(['name' => 'Basset de los Alpes', 'id_specie' => '1']);
        Race::create(['name' => 'Basset Hound', 'id_specie' => '1']);
        Race::create(['name' => 'Beagle', 'id_specie' => '1']);
        Race::create(['name' => 'Beagle-Harrier', 'id_specie' => '1']);
        Race::create(['name' => 'Beauceron', 'id_specie' => '1']);
        Race::create(['name' => 'Bedlington Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Bergamasco', 'id_specie' => '1']);
        Race::create(['name' => 'Bichón boloñés', 'id_specie' => '1']);
        Race::create(['name' => 'Bichón frisé', 'id_specie' => '1']);
        Race::create(['name' => 'Bichón Habanero', 'id_specie' => '1']);
        Race::create(['name' => 'Bichón maltés', 'id_specie' => '1']);
        Race::create(['name' => 'Bobtail', 'id_specie' => '1']);
        Race::create(['name' => 'Boerboel', 'id_specie' => '1']);
        Race::create(['name' => 'Border collie', 'id_specie' => '1']);
        Race::create(['name' => 'Border Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Borzoi', 'id_specie' => '1']);
        Race::create(['name' => 'Boston terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Bóxer', 'id_specie' => '1']);
        Race::create(['name' => 'Boyero de Berna', 'id_specie' => '1']);
        Race::create(['name' => 'Boyero de Entlebuch', 'id_specie' => '1']);
        Race::create(['name' => 'Boyero de las Ardenas', 'id_specie' => '1']);
        Race::create(['name' => 'Braco alemán', 'id_specie' => '1']);
        Race::create(['name' => 'Braco alemán de pelo corto', 'id_specie' => '1']);
        Race::create(['name' => 'Braco húngaro', 'id_specie' => '1']);
        Race::create(['name' => 'Bull Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Bulldog Americano', 'id_specie' => '1']);
        Race::create(['name' => 'Bulldog francés', 'id_specie' => '1']);
        Race::create(['name' => 'Bulldog inglés', 'id_specie' => '1']);
        Race::create(['name' => 'Bullmastiff', 'id_specie' => '1']);
        Race::create(['name' => 'Cairn Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Cane Corso', 'id_specie' => '1']);
        Race::create(['name' => 'Cavalier King Charles Spaniel', 'id_specie' => '1']);
        Race::create(['name' => 'Chihuahua', 'id_specie' => '1']);
        Race::create(['name' => 'Chow Chow', 'id_specie' => '1']);
        Race::create(['name' => 'Cirneco del Etna', 'id_specie' => '1']);
        Race::create(['name' => 'Cobrador de pelo liso', 'id_specie' => '1']);
        Race::create(['name' => 'Cocker Spaniel americano', 'id_specie' => '1']);
        Race::create(['name' => 'Cocker Spaniel inglés', 'id_specie' => '1']);
        Race::create(['name' => 'Collie barbudo', 'id_specie' => '1']);
        Race::create(['name' => 'Collie de pelo largo', 'id_specie' => '1']);
        Race::create(['name' => 'Corgi galés de Pembroke', 'id_specie' => '1']);
        Race::create(['name' => 'Cotón de Tulear', 'id_specie' => '1']);
        Race::create(['name' => 'Crestado chino', 'id_specie' => '1']);
        Race::create(['name' => 'Crestado rodesiano', 'id_specie' => '1']);
        Race::create(['name' => 'Dálmata', 'id_specie' => '1']);
        Race::create(['name' => 'Dandie Dinmont', 'id_specie' => '1']);
        Race::create(['name' => 'Dóberman', 'id_specie' => '1']);
        Race::create(['name' => 'Dogo argentino', 'id_specie' => '1']);
        Race::create(['name' => 'Dogo de Burdeos', 'id_specie' => '1']);
        Race::create(['name' => 'Drever', 'id_specie' => '1']);
        Race::create(['name' => 'Eurasier', 'id_specie' => '1']);
        Race::create(['name' => 'Fila Brasileiro', 'id_specie' => '1']);
        Race::create(['name' => 'Fox Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Foxhound americano', 'id_specie' => '1']);
        Race::create(['name' => 'French poodle', 'id_specie' => '1']);
        Race::create(['name' => 'Galgo afgano', 'id_specie' => '1']);
        Race::create(['name' => 'Galgo español', 'id_specie' => '1']);
        Race::create(['name' => 'Galgo inglés', 'id_specie' => '1']);
        Race::create(['name' => 'Galgo italiano', 'id_specie' => '1']);
        Race::create(['name' => 'Golden Retriever', 'id_specie' => '1']);
        Race::create(['name' => 'Gran boyero suizo', 'id_specie' => '1']);
        Race::create(['name' => 'Gran danés', 'id_specie' => '1']);
        Race::create(['name' => 'Grifón de Bruselas', 'id_specie' => '1']);
        Race::create(['name' => 'Husky siberiano', 'id_specie' => '1']);
        Race::create(['name' => 'Jack Russell Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Kelpie australiano', 'id_specie' => '1']);
        Race::create(['name' => 'Komondor', 'id_specie' => '1']);
        Race::create(['name' => 'Labrador Retriever', 'id_specie' => '1']);
        Race::create(['name' => 'Lagotto Romagnolo', 'id_specie' => '1']);
        Race::create(['name' => 'Lebrel irlandés', 'id_specie' => '1']);
        Race::create(['name' => 'Leonberger', 'id_specie' => '1']);
        Race::create(['name' => 'Lhasa Apso', 'id_specie' => '1']);
        Race::create(['name' => 'Mastín del Pirineo', 'id_specie' => '1']);
        Race::create(['name' => 'Mastín español', 'id_specie' => '1']);
        Race::create(['name' => 'Mastín inglés', 'id_specie' => '1']);
        Race::create(['name' => 'Mastín napolitano', 'id_specie' => '1']);
        Race::create(['name' => 'Mastín tibetano', 'id_specie' => '1']);
        Race::create(['name' => 'Mudi', 'id_specie' => '1']);
        Race::create(['name' => 'Otterhound', 'id_specie' => '1']);
        Race::create(['name' => 'Papillón', 'id_specie' => '1']);
        Race::create(['name' => 'Parson Russell Terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor alemán', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor australiano', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor belga', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor Blanco Suizo', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor de Anatolia', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor de Brie', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor de las islas Shetland', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor de Maremma', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor ganadero australiano', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor holandés', 'id_specie' => '1']);
        Race::create(['name' => 'Pastor mallorquín', 'id_specie' => '1']);
        Race::create(['name' => 'Pekinés', 'id_specie' => '1']);
        Race::create(['name' => 'Pequeño perro león', 'id_specie' => '1']);
        Race::create(['name' => 'Perdiguero de Burgos', 'id_specie' => '1']);
        Race::create(['name' => 'Perro de agua español', 'id_specie' => '1']);
        Race::create(['name' => 'Perro de agua portugués', 'id_specie' => '1']);
        Race::create(['name' => 'Perro de montaña de los Pirineos', 'id_specie' => '1']);
        Race::create(['name' => 'Perro de San Huberto', 'id_specie' => '1']);
        Race::create(['name' => 'Perro esquimal canadiense', 'id_specie' => '1']);
        Race::create(['name' => 'Perro lobo checoslovaco', 'id_specie' => '1']);
        Race::create(['name' => 'Perro lobo de Saarloos', 'id_specie' => '1']);
        Race::create(['name' => 'Perro pastor catalán', 'id_specie' => '1']);
        Race::create(['name' => 'Perro pastor de Asia central', 'id_specie' => '1']);
        Race::create(['name' => 'Perro salchicha', 'id_specie' => '1']);
        Race::create(['name' => 'Perro sin pelo del Perú', 'id_specie' => '1']);
        Race::create(['name' => 'Pinscher', 'id_specie' => '1']);
        Race::create(['name' => 'Podenco ibicenco', 'id_specie' => '1']);
        Race::create(['name' => 'Podenco portugués', 'id_specie' => '1']);
        Race::create(['name' => 'Pointer inglés', 'id_specie' => '1']);
        Race::create(['name' => 'Pomerania', 'id_specie' => '1']);
        Race::create(['name' => 'Presa Canario', 'id_specie' => '1']);
        Race::create(['name' => 'Pug', 'id_specie' => '1']);
        Race::create(['name' => 'Retriever de Nueva Escocia', 'id_specie' => '1']);
        Race::create(['name' => 'Rottweiler', 'id_specie' => '1']);
        Race::create(['name' => 'Saluki', 'id_specie' => '1']);
        Race::create(['name' => 'Samoyedo', 'id_specie' => '1']);
        Race::create(['name' => 'San Bernardo', 'id_specie' => '1']);
        Race::create(['name' => 'Schipperke', 'id_specie' => '1']);
        Race::create(['name' => 'Schnauzer', 'id_specie' => '1']);
        Race::create(['name' => 'Setter irlandés', 'id_specie' => '1']);
        Race::create(['name' => 'Shar Pei', 'id_specie' => '1']);
        Race::create(['name' => 'Shiba Inu', 'id_specie' => '1']);
        Race::create(['name' => 'Shih tzu', 'id_specie' => '1']);
        Race::create(['name' => 'Shikoku Inu', 'id_specie' => '1']);
        Race::create(['name' => 'Spaniel bretón', 'id_specie' => '1']);
        Race::create(['name' => 'Spaniel tibetano', 'id_specie' => '1']);
        Race::create(['name' => 'Spitz finlandés', 'id_specie' => '1']);
        Race::create(['name' => 'Spitz japonés', 'id_specie' => '1']);
        Race::create(['name' => 'Staffordshire bull terrier', 'id_specie' => '1']);
        Race::create(['name' => 'Terranova', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier alemán', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier australiano', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier escocés', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier galés', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier irlandés', 'id_specie' => '1']);
        Race::create(['name' => 'Terrier tibetano', 'id_specie' => '1']);
        Race::create(['name' => 'Vizsla', 'id_specie' => '1']);
        Race::create(['name' => 'Volpino italiano', 'id_specie' => '1']);
        Race::create(['name' => 'Weimaraner', 'id_specie' => '1']);
        Race::create(['name' => 'Westie', 'id_specie' => '1']);
        Race::create(['name' => 'Whippet', 'id_specie' => '1']);
        Race::create(['name' => 'Xoloitzcuintle', 'id_specie' => '1']);
        Race::create(['name' => 'Yorkshire Terrier', 'id_specie' => '1']);

        Race::create(['name' => 'Abisinio', 'id_specie' => '2']);
        Race::create(['name' => 'American Shorthair', 'id_specie' => '2']);
        Race::create(['name' => 'American Wirehair', 'id_specie' => '2']);
        Race::create(['name' => 'Angora turco', 'id_specie' => '2']);
        Race::create(['name' => 'Azul ruso', 'id_specie' => '2']);
        Race::create(['name' => 'Balinés', 'id_specie' => '2']);
        Race::create(['name' => 'Bengala', 'id_specie' => '2']);
        Race::create(['name' => 'Birmano', 'id_specie' => '2']);
        Race::create(['name' => 'Bobtail Americano', 'id_specie' => '2']);
        Race::create(['name' => 'Bobtail japonés', 'id_specie' => '2']);
        Race::create(['name' => 'Bombay', 'id_specie' => '2']);
        Race::create(['name' => 'Bosque de Noruega', 'id_specie' => '2']);
        Race::create(['name' => 'British Longhair', 'id_specie' => '2']);
        Race::create(['name' => 'British Shorthair', 'id_specie' => '2']);
        Race::create(['name' => 'Burmilla', 'id_specie' => '2']);
        Race::create(['name' => 'California Spangled', 'id_specie' => '2']);
        Race::create(['name' => 'Californian Rex', 'id_specie' => '2']);
        Race::create(['name' => 'Cartujo', 'id_specie' => '2']);
        Race::create(['name' => 'Ceilán', 'id_specie' => '2']);
        Race::create(['name' => 'Chausie', 'id_specie' => '2']);
        Race::create(['name' => 'Cornish Rex', 'id_specie' => '2']);
        Race::create(['name' => 'Curl americano', 'id_specie' => '2']);
        Race::create(['name' => 'Cymric', 'id_specie' => '2']);
        Race::create(['name' => 'Devon Rex', 'id_specie' => '2']);
        Race::create(['name' => 'Don Sphynx', 'id_specie' => '2']);
        Race::create(['name' => 'Exótico', 'id_specie' => '2']);
        Race::create(['name' => 'Gato común', 'id_specie' => '2']);
        Race::create(['name' => 'Gato común europeo', 'id_specie' => '2']);
        Race::create(['name' => 'Gato esfinge', 'id_specie' => '2']);
        Race::create(['name' => 'Gato Siberiano', 'id_specie' => '2']);
        Race::create(['name' => 'Gato Van turco', 'id_specie' => '2']);
        Race::create(['name' => 'German Rex', 'id_specie' => '2']);
        Race::create(['name' => 'Habana Brown', 'id_specie' => '2']);
        Race::create(['name' => 'Highland Fold y Highland Straight', 'id_specie' => '2']);
        Race::create(['name' => 'Himalayo', 'id_specie' => '2']);
        Race::create(['name' => 'Javanés', 'id_specie' => '2']);
        Race::create(['name' => 'Khao Manee', 'id_specie' => '2']);
        Race::create(['name' => 'Korat', 'id_specie' => '2']);
        Race::create(['name' => 'LaPerm', 'id_specie' => '2']);
        Race::create(['name' => 'Maine Coon', 'id_specie' => '2']);
        Race::create(['name' => 'Manx', 'id_specie' => '2']);
        Race::create(['name' => 'Mau egipcio', 'id_specie' => '2']);
        Race::create(['name' => 'Munchkin', 'id_specie' => '2']);
        Race::create(['name' => 'Nebelung', 'id_specie' => '2']);
        Race::create(['name' => 'Ocicat', 'id_specie' => '2']);
        Race::create(['name' => 'Oriental', 'id_specie' => '2']);
        Race::create(['name' => 'Persa', 'id_specie' => '2']);
        Race::create(['name' => 'Persa Chinchilla', 'id_specie' => '2']);
        Race::create(['name' => 'Peterbald', 'id_specie' => '2']);
        Race::create(['name' => 'Pixie Bob', 'id_specie' => '2']);
        Race::create(['name' => 'Ragamuffin', 'id_specie' => '2']);
        Race::create(['name' => 'Ragdoll', 'id_specie' => '2']);
        Race::create(['name' => 'Safari', 'id_specie' => '2']);
        Race::create(['name' => 'Sagrado de Birmania', 'id_specie' => '2']);
        Race::create(['name' => 'Savannah', 'id_specie' => '2']);
        Race::create(['name' => 'Scottish Fold', 'id_specie' => '2']);
        Race::create(['name' => 'Selkirk Rex', 'id_specie' => '2']);
        Race::create(['name' => 'Siamés', 'id_specie' => '2']);
        Race::create(['name' => 'Siamés thai', 'id_specie' => '2']);
        Race::create(['name' => 'Singapura', 'id_specie' => '2']);
        Race::create(['name' => 'Snowshoe', 'id_specie' => '2']);
        Race::create(['name' => 'Sokoke', 'id_specie' => '2']);
        Race::create(['name' => 'Somalí', 'id_specie' => '2']);
        Race::create(['name' => 'Tiffany', 'id_specie' => '2']);
        Race::create(['name' => 'Tonkinés', 'id_specie' => '2']);
        Race::create(['name' => 'Toyger', 'id_specie' => '2']);
        Race::create(['name' => 'York Chocolate', 'id_specie' => '2']);
    }
}
